import { useEffect, useState } from 'react';
import { CalendarDays, MapPin, Ticket, QrCode } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { useOrganisationCurrency } from '@/lib/useOrganisationCurrency';
import { formatCurrency } from '@/lib/utils';
import { supabase } from '@/lib/supabase';
import { PageHeader } from '@/components/ui/PageHeader';

interface EventRow{id:string;title:string;description:string|null;venue:string|null;start_at:string;status:string;event_ticket_types?:{id:string;name:string;price:number;member_price:number|null}[]}
interface TicketRow{id:string;qr_token:string;status:string;attendee_name:string;events:any;event_ticket_types:any}
export function MemberEvents(){const {activeOrg,profile}=useAuth();const {currency}=useOrganisationCurrency();const [events,setEvents]=useState<EventRow[]>([]);const [tickets,setTickets]=useState<TicketRow[]>([]);useEffect(()=>{if(!activeOrg)return;supabase.from('events').select('*,event_ticket_types(*)').eq('organisation_id',activeOrg.id).eq('status','published').gte('start_at',new Date().toISOString()).order('start_at').then(({data})=>setEvents((data??[]) as EventRow[]));if(profile){supabase.from('members').select('id').eq('organisation_id',activeOrg.id).eq('user_id',profile.id).maybeSingle().then(({data:m})=>{if(m)supabase.from('event_tickets').select('*,events(title,start_at,venue),event_ticket_types(name)').eq('member_id',m.id).order('created_at',{ascending:false}).then(({data})=>setTickets((data??[]) as TicketRow[]));});}},[activeOrg,profile]);return <div className="space-y-6"><PageHeader title="Events" description="Club events, registrations and your QR tickets."/>{tickets.length>0&&<section><h2 className="mb-3 font-semibold">My tickets</h2><div className="grid gap-4 md:grid-cols-2">{tickets.map(t=><div className="card p-5" key={t.id}><div className="flex justify-between gap-4"><div><p className="font-semibold">{t.events?.title}</p><p className="text-sm text-slate-500">{t.event_ticket_types?.name} · {t.attendee_name}</p><p className="mt-2 text-xs font-medium uppercase text-slate-500">{t.status}</p></div><img className="h-28 w-28 rounded border bg-white p-1" alt="Ticket QR code" src={`https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(t.qr_token)}`}/></div><p className="mt-3 break-all rounded bg-slate-50 p-2 font-mono text-xs">{t.qr_token}</p></div>)}</div></section>}<section><h2 className="mb-3 font-semibold">Upcoming events</h2><div className="grid gap-4 md:grid-cols-2">{events.map(e=><div className="card p-5" key={e.id}><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-primary-700"/><h3 className="font-semibold">{e.title}</h3></div><p className="mt-2 text-sm text-slate-500">{e.description}</p><div className="mt-4 space-y-2 text-sm"><p>{new Date(e.start_at).toLocaleString('en-NZ',{dateStyle:'medium',timeStyle:'short'})}</p><p className="flex gap-2"><MapPin className="h-4 w-4"/>{e.venue??'Venue TBC'}</p></div><div className="mt-4 flex flex-wrap gap-2">{e.event_ticket_types?.map(tt=><span className="rounded-full bg-primary-50 px-3 py-1 text-xs text-primary-800" key={tt.id}><Ticket className="mr-1 inline h-3 w-3"/>{tt.name}: {Number(tt.member_price??tt.price)===0?'Free':formatCurrency(Number(tt.member_price??tt.price),currency)}</span>)}</div><button className="btn-primary mt-4" title="Payment checkout will connect to Stripe/POLi"><QrCode className="h-4 w-4"/> Register / Buy ticket</button></div>)}</div></section></div>}
