import { useEffect, useMemo, useState } from 'react';
import { CreditCard, AlertCircle, CheckCircle2, ShoppingBag, Heart, Users, Calendar } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import { useOrganisationCurrency } from '@/lib/useOrganisationCurrency';
import { formatCurrency } from '@/lib/utils';
import { notifySuccess } from '@/lib/notifications';

type PaymentItem={id:string;kind:'subscription'|'donation'|'merchandise'|'event';title:string;detail:string;amount:number;status:string;date:string};
export function MemberPayments(){
 const {activeOrg,profile}=useAuth(); const {currency}=useOrganisationCurrency(); const [memberId,setMemberId]=useState<string|null>(null); const [items,setItems]=useState<PaymentItem[]>([]); const [history,setHistory]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [paying,setPaying]=useState<string|null>(null);
 async function load(){if(!activeOrg||!profile)return;setLoading(true);const {data:m}=await supabase.from('members').select('id').eq('organisation_id',activeOrg.id).eq('user_id',profile.id).maybeSingle();const mid=m?.id??null;setMemberId(mid);const [charges,donations,merch,eventOrders,tx]=await Promise.all([
  mid?supabase.from('member_subscription_charges').select('id,amount,status,season,due_date,created_at,teams(name),subscription_types(name)').eq('organisation_id',activeOrg.id).eq('member_id',mid).order('created_at',{ascending:false}):Promise.resolve({data:[]}),
  mid?supabase.from('donations').select('id,campaign,amount,status,donated_at').eq('organisation_id',activeOrg.id).eq('member_id',mid).order('donated_at',{ascending:false}):Promise.resolve({data:[]}),
  supabase.from('merchandise_orders').select('id,total_amount,payment_status,created_at,merchandise_products(name)').eq('organisation_id',activeOrg.id).eq('purchaser_user_id',profile.id).order('created_at',{ascending:false}),
  mid?supabase.from('event_orders').select('id,total_amount,payment_status,created_at,events(title)').eq('organisation_id',activeOrg.id).eq('member_id',mid).order('created_at',{ascending:false}):Promise.resolve({data:[]}),
  mid?supabase.from('club_finance_transactions').select('id,reference,description,amount,status,provider,occurred_at,transaction_type').eq('organisation_id',activeOrg.id).eq('member_id',mid).order('occurred_at',{ascending:false}).limit(30):Promise.resolve({data:[]})
 ]);
 const all:PaymentItem[]=[];(charges.data??[]).forEach((x:any)=>all.push({id:x.id,kind:'subscription',title:x.subscription_types?.name||'Team subscription',detail:`${x.teams?.name||'Team'}${x.season?` · ${x.season}`:''}`,amount:Number(x.amount||0),status:x.status,date:x.due_date||x.created_at}));(donations.data??[]).forEach((x:any)=>all.push({id:x.id,kind:'donation',title:x.campaign||'Donation',detail:'Club donation',amount:Number(x.amount||0),status:x.status,date:x.donated_at}));(merch.data??[]).forEach((x:any)=>all.push({id:x.id,kind:'merchandise',title:x.merchandise_products?.name||'Merchandise order',detail:'Club shop',amount:Number(x.total_amount||0),status:x.payment_status,date:x.created_at}));(eventOrders.data??[]).forEach((x:any)=>all.push({id:x.id,kind:'event',title:x.events?.title||'Event tickets',detail:'Event order',amount:Number(x.total_amount||0),status:x.payment_status,date:x.created_at}));setItems(all);setHistory(tx.data??[]);setLoading(false)}
 useEffect(()=>{load()},[activeOrg?.id,profile?.id]);
 const pending=useMemo(()=>items.filter(x=>['pending','unpaid'].includes(String(x.status).toLowerCase())&&x.amount>0),[items]);const outstanding=pending.reduce((n,x)=>n+x.amount,0);const paidTotal=history.filter(x=>x.status==='paid').reduce((n,x)=>n+Number(x.amount||0),0);
 async function pay(item:PaymentItem){if(!activeOrg||!profile)return;if(!confirm(`Pay ${formatCurrency(item.amount,currency)} for ${item.title}?\n\nThis demo records the payment in ClubOS. Connect Stripe/POLi before using this for live card or bank payments.`))return;setPaying(item.id);const {error}=await supabase.rpc('record_demo_member_payment',{p_item_type:item.kind,p_item_id:item.id});setPaying(null);if(error){alert(error.message);return}notifySuccess('Payment recorded successfully.');await load()}
 const icon=(kind:string)=>kind==='subscription'?<Users className="h-5 w-5"/>:kind==='donation'?<Heart className="h-5 w-5"/>:kind==='merchandise'?<ShoppingBag className="h-5 w-5"/>:<Calendar className="h-5 w-5"/>;
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Payments</h1><p className="mt-1 text-sm text-slate-500">Pay team subscriptions, donations, merchandise and event orders.</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="card p-5"><p className="text-xs uppercase text-slate-400">Outstanding</p><p className="mt-1 text-2xl font-bold text-amber-700">{formatCurrency(outstanding,currency)}</p><p className="mt-1 text-sm text-slate-500">{pending.length} pending item{pending.length===1?'':'s'}</p></div><div className="card p-5"><p className="text-xs uppercase text-slate-400">Recorded paid</p><p className="mt-1 text-2xl font-bold text-emerald-700">{formatCurrency(paidTotal,currency)}</p></div></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertCircle className="mr-2 inline h-4 w-4"/><b>Demo payment flow:</b> the Pay Now button records a successful test payment. Connect Stripe/POLi checkout and webhooks before accepting real money.</div><div className="card overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Pending payments</h2></div>{loading?<div className="p-8 text-center">Loading…</div>:pending.length===0?<div className="p-8 text-center text-slate-500"><CheckCircle2 className="mx-auto mb-2 h-8 w-8 text-emerald-500"/>Nothing outstanding.</div>:<div className="divide-y">{pending.map(x=><div key={`${x.kind}-${x.id}`} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary-50 text-primary-700">{icon(x.kind)}</div><div><p className="font-medium">{x.title}</p><p className="text-sm text-slate-500">{x.detail}</p><p className="text-xs capitalize text-slate-400">{x.kind}</p></div></div><div className="flex items-center justify-between gap-4 sm:justify-end"><p className="text-lg font-semibold">{formatCurrency(x.amount,currency)}</p><button className="btn-primary" disabled={paying===x.id} onClick={()=>pay(x)}><CreditCard className="h-4 w-4"/>{paying===x.id?'Processing…':'Pay Now'}</button></div></div>)}</div>}</div><div className="card overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Payment history</h2></div>
 <div className="sm:hidden">{history.length===0?<div className="p-8 text-center text-slate-500">No recorded payments yet.</div>:<div className="divide-y">{history.map(x=><div key={x.id} className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-medium text-slate-900">{x.description}</p><p className="mt-1 text-xs text-slate-500">{x.reference} · {x.provider||'—'}</p></div><p className="shrink-0 font-semibold">{formatCurrency(Number(x.amount||0),currency)}</p></div><p className="mt-2 text-xs capitalize text-slate-500">{x.status}</p></div>)}</div>}</div>
 <div className="hidden overflow-x-auto sm:block"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Reference</th><th className="px-4 py-3">Description</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Method</th></tr></thead><tbody className="divide-y">{history.length===0?<tr><td colSpan={5} className="p-8 text-center text-slate-500">No recorded payments yet.</td></tr>:history.map(x=><tr key={x.id}><td className="px-4 py-3">{x.reference}</td><td className="px-4 py-3">{x.description}</td><td className="px-4 py-3 font-medium">{formatCurrency(Number(x.amount||0),currency)}</td><td className="px-4 py-3 capitalize">{x.status}</td><td className="px-4 py-3">{x.provider||'—'}</td></tr>)}</tbody></table></div></div></div>
}
