import { useEffect, useState } from 'react';
import { ShoppingBag, Image as ImageIcon } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import { formatCurrency } from '@/lib/utils';
import { useOrganisationCurrency } from '@/lib/useOrganisationCurrency';

type Product={id:string;name:string;description:string|null;price:number;stock_quantity:number;status:string;image_url_1:string|null;image_url_2:string|null};
export function MemberMerchandise(){const {activeOrg,profile}=useAuth();const {currency}=useOrganisationCurrency();const [rows,setRows]=useState<Product[]>([]);useEffect(()=>{if(!activeOrg)return;supabase.from('merchandise_products').select('*').eq('organisation_id',activeOrg.id).eq('status','active').order('name').then(({data})=>setRows((data??[]) as Product[]))},[activeOrg?.id]);async function purchase(p:Product){if(!activeOrg||!profile||p.stock_quantity<=0)return;const qty=Number(window.prompt(`Quantity for ${p.name}?`,'1')||0);if(!Number.isInteger(qty)||qty<1)return;if(qty>p.stock_quantity){alert('Not enough stock available.');return}const {error}=await supabase.from('merchandise_orders').insert({organisation_id:activeOrg.id,product_id:p.id,purchaser_user_id:profile.id,quantity:qty,unit_price:Number(p.price),total_amount:Number(p.price)*qty,payment_status:Number(p.price)===0?'free':'pending'});if(error)alert(error.message);else alert(Number(p.price)===0?'Order created.':'Order created and is pending payment through the configured payment provider.')} return <div className="space-y-5"><div><h1 className="text-2xl font-bold">Club Merchandise</h1><p className="text-sm text-slate-500">Browse products and view both product images before purchasing.</p></div><div className="grid gap-4 sm:grid-cols-2">{rows.map(p=><div className="card overflow-hidden" key={p.id}><div className="grid grid-cols-2 bg-slate-100">{[p.image_url_1,p.image_url_2].map((u,i)=>u?<img src={u} key={i} className="h-44 w-full object-cover" alt={`${p.name} ${i+1}`}/>:<div key={i} className="flex h-44 items-center justify-center text-slate-300"><ImageIcon/></div>)}</div><div className="p-4"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold">{p.name}</h2><span className="font-bold text-primary-700">{formatCurrency(Number(p.price),currency)}</span></div><p className="mt-2 text-sm text-slate-600">{p.description}</p><p className="mt-3 text-xs text-slate-500">{p.stock_quantity>0?`${p.stock_quantity} available`:'Out of stock'}</p><button className="btn-primary mt-4 w-full" disabled={p.stock_quantity<=0} onClick={()=>purchase(p)}><ShoppingBag className="h-4 w-4"/> Purchase</button></div></div>)}</div>{rows.length===0&&<div className="card p-8 text-center text-slate-500">No merchandise is currently available.</div>}</div>}
