import { useEffect, useState } from 'react';
import { Heart, Gift } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import { FormField, TextInput } from '@/components/ui/FormField';
import { useOrganisationCurrency } from '@/lib/useOrganisationCurrency';
import { formatCurrency } from '@/lib/utils';
import { notifySuccess } from '@/lib/notifications';

export function MemberDonations(){
 const {activeOrg,profile}=useAuth(); const {currency}=useOrganisationCurrency();
 const [memberId,setMemberId]=useState<string|null>(null); const [amount,setAmount]=useState('50'); const [campaign,setCampaign]=useState('General Club Donation'); const [message,setMessage]=useState(''); const [history,setHistory]=useState<any[]>([]); const [saving,setSaving]=useState(false);
 async function load(){if(!activeOrg||!profile)return;const {data:m}=await supabase.from('members').select('id,first_name,last_name,preferred_name').eq('organisation_id',activeOrg.id).eq('user_id',profile.id).maybeSingle();setMemberId(m?.id??null);if(m?.id){const {data}=await supabase.from('donations').select('*').eq('organisation_id',activeOrg.id).eq('member_id',m.id).order('donated_at',{ascending:false}).limit(20);setHistory(data??[])}}
 useEffect(()=>{load()},[activeOrg?.id,profile?.id]);
 async function donate(){if(!activeOrg||!profile||!memberId)return;const value=Number(amount);if(!Number.isFinite(value)||value<=0){setMessage('Enter a donation amount greater than zero.');return}setSaving(true);setMessage('');const {error}=await supabase.from('donations').insert({organisation_id:activeOrg.id,member_id:memberId,donor_name:`${profile.first_name??''} ${profile.last_name??''}`.trim()||profile.email,campaign:campaign.trim()||'General Club Donation',amount:value,provider:'online',status:'pending',donated_at:new Date().toISOString()});setSaving(false);if(error){setMessage(error.message);return}notifySuccess('Donation added to your pending payments.');setMessage('Donation created. Open Payments to complete it.');await load()}
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Donations</h1><p className="mt-1 text-sm text-slate-500">Support your club. New donations are added to your Payments page until payment is completed.</p></div><div className="grid gap-5 lg:grid-cols-[1fr_0.8fr]"><div className="card p-6"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-rose-50 text-rose-600"><Heart className="h-5 w-5"/></div><div><h2 className="font-semibold">Make a donation</h2><p className="text-sm text-slate-500">Choose any amount.</p></div></div><div className="mt-5 space-y-4"><FormField label={`Amount (${currency})`}><TextInput type="number" min="1" step="1" value={amount} onChange={e=>setAmount(e.target.value)}/></FormField><FormField label="Campaign / purpose"><TextInput value={campaign} onChange={e=>setCampaign(e.target.value)} placeholder="General Club Donation"/></FormField>{message&&<div className="rounded-lg bg-slate-50 p-3 text-sm text-slate-700">{message}</div>}<button className="btn-primary w-full" disabled={saving} onClick={donate}><Gift className="h-4 w-4"/> {saving?'Saving…':`Donate ${formatCurrency(Number(amount||0),currency)}`}</button></div></div><div className="card p-6"><h2 className="font-semibold">My donations</h2><div className="mt-4 space-y-3">{history.length===0?<p className="text-sm text-slate-500">No donations recorded yet.</p>:history.map(d=><div key={d.id} className="rounded-lg border p-3"><div className="flex justify-between gap-3"><div><p className="font-medium">{d.campaign||'Donation'}</p><p className="text-xs text-slate-500">{new Date(d.donated_at).toLocaleDateString()}</p></div><div className="text-right"><p className="font-semibold">{formatCurrency(Number(d.amount||0),currency)}</p><p className="text-xs capitalize text-slate-500">{d.status}</p></div></div></div>)}</div></div></div></div>
}
