import { useEffect, useMemo, useState } from 'react';
import { Search, Plus, Download, Pencil, Trash2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { Modal } from '@/components/ui/Modal';
import { notifySuccess } from '@/lib/notifications';
type Row=Record<string,string|number>;
type Config={title:string;subtitle:string;metrics:[string,string][];columns:string[];rows:Row[]};
const data:Record<string,Config>={
 organisations:{title:'Organisations',subtitle:'Clubs and associations using ClubOS.',metrics:[['Organisations','12'],['Active','10'],['Trial','1'],['Suspended','1']],columns:['Organisation','Plan','Members','MRR','Status'],rows:[{Organisation:'Demo Sports Club',Plan:'Pro',Members:158,MRR:'$149',Status:'Active'},{Organisation:'Harbour Cricket Club',Plan:'Standard',Members:284,MRR:'$99',Status:'Active'},{Organisation:'Wellington Community Netball',Plan:'Pro',Members:412,MRR:'$149',Status:'Active'},{Organisation:'Eastern Juniors FC',Plan:'Starter',Members:96,MRR:'$49',Status:'Trial'}]},
 plans:{title:'Subscription Plans',subtitle:'Pricing tiers and included platform capability.',metrics:[['Plans','4'],['Subscribers','12'],['MRR','$1,338'],['Trial conversion','72%']],columns:['Plan','Monthly price','Organisations','Member limit','Status'],rows:[{Plan:'Starter','Monthly price':'$49',Organisations:3,'Member limit':150,Status:'Active'},{Plan:'Standard','Monthly price':'$99',Organisations:4,'Member limit':500,Status:'Active'},{Plan:'Pro','Monthly price':'$149',Organisations:4,'Member limit':1500,Status:'Active'},{Plan:'Enterprise','Monthly price':'Custom',Organisations:1,'Member limit':'Unlimited',Status:'Active'}]},
 modules:{title:'Modules & Add-ons',subtitle:'Platform feature catalogue and commercial add-ons.',metrics:[['Modules','16'],['Core','6'],['Add-ons','10'],['Most popular','Events']],columns:['Module','Category','Base price','Adoption','Status'],rows:[{Module:'Membership',Category:'Core','Base price':'Included',Adoption:'100%',Status:'Active'},{Module:'Events & Ticketing',Category:'Operations','Base price':'Included',Adoption:'83%',Status:'Active'},{Module:'Merchandise',Category:'Commerce','Base price':'$19/mo',Adoption:'58%',Status:'Active'},{Module:'Donations',Category:'Commerce','Base price':'$9/mo',Adoption:'50%',Status:'Active'},{Module:'Advanced Compliance',Category:'Governance','Base price':'$29/mo',Adoption:'33%',Status:'Active'}]},
 subscriptions:{title:'Subscriptions',subtitle:'Organisation subscription status and renewals.',metrics:[['Active subscriptions','10'],['Trials','1'],['Past due','1'],['Next renewals','4']],columns:['Organisation','Plan','Started','Next billing','Status'],rows:[{Organisation:'Demo Sports Club',Plan:'Pro',Started:'1 Jul 2026','Next billing':'1 Sep 2026',Status:'Active'},{Organisation:'Harbour Cricket Club',Plan:'Standard',Started:'15 May 2026','Next billing':'15 Sep 2026',Status:'Active'},{Organisation:'Eastern Juniors FC',Plan:'Starter',Started:'20 Aug 2026','Next billing':'3 Sep 2026',Status:'Trial'}]},
 billing:{title:'Platform Billing',subtitle:'SaaS invoices, collections and payment provider status.',metrics:[['MRR','$1,338'],['Collected','$1,239'],['Outstanding','$198'],['Failed payments','1']],columns:['Invoice','Organisation','Amount','Provider','Status'],rows:[{Invoice:'INV-PLT-2081',Organisation:'Demo Sports Club',Amount:'$149',Provider:'Stripe',Status:'Paid'},{Invoice:'INV-PLT-2080',Organisation:'Harbour Cricket Club',Amount:'$99',Provider:'Stripe',Status:'Paid'},{Invoice:'INV-PLT-2076',Organisation:'City Social Club',Amount:'$99',Provider:'Stripe',Status:'Past due'}]},
 usage:{title:'Platform Usage',subtitle:'Current consumption by tenant and feature.',metrics:[['Members stored','3,842'],['Emails / month','18,420'],['Event scans','2,176'],['Storage','8.4 GB']],columns:['Organisation','Members','Emails','Storage','API calls'],rows:[{Organisation:'Demo Sports Club',Members:158,Emails:1248,Storage:'0.7 GB','API calls':'18.4k'},{Organisation:'Harbour Cricket Club',Members:284,Emails:2160,Storage:'1.2 GB','API calls':'32.8k'},{Organisation:'Wellington Community Netball',Members:412,Emails:3524,Storage:'1.8 GB','API calls':'47.1k'}]},
 support:{title:'Support',subtitle:'Customer support queue and service requests.',metrics:[['Open tickets','7'],['High priority','1'],['Avg response','42m'],['SLA met','97%']],columns:['Ticket','Organisation','Subject','Priority','Status'],rows:[{Ticket:'SUP-1028',Organisation:'Harbour Cricket Club',Subject:'Member import question',Priority:'Normal',Status:'Open'},{Ticket:'SUP-1027',Organisation:'Demo Sports Club',Subject:'POLi configuration',Priority:'Normal',Status:'Waiting customer'},{Ticket:'SUP-1024',Organisation:'City Social Club',Subject:'Payment webhook failure',Priority:'High',Status:'Investigating'}]},
 privacy:{title:'Privacy & Compliance',subtitle:'Cross-platform privacy and compliance oversight.',metrics:[['Open privacy requests','3'],['Incidents','0'],['Consent avg','95%'],['Audits due','2']],columns:['Organisation','Area','Issue','Due','Status'],rows:[{Organisation:'Demo Sports Club',Area:'Privacy',Issue:'Member access request',Due:'4 Sep 2026',Status:'Open'},{Organisation:'Harbour Cricket Club',Area:'Retention',Issue:'Inactive member purge',Due:'1 Sep 2026',Status:'Scheduled'},{Organisation:'Eastern Juniors FC',Area:'Consent',Issue:'Junior photo consents incomplete',Due:'31 Aug 2026',Status:'Action required'}]},
 users:{title:'Platform Users',subtitle:'Super administrators and support operators.',metrics:[['Platform users','5'],['Super admins','2'],['Support','2'],['Billing','1']],columns:['Name','Role','Email','Last active','Status'],rows:[{Name:'Platform Admin',Role:'Super Admin',Email:'platform.admin@clubos.example','Last active':'Today',Status:'Active'},{Name:'Alex Morgan',Role:'Support',Email:'alex@clubos.example','Last active':'Today',Status:'Active'},{Name:'Priya Singh',Role:'Support',Email:'priya@clubos.example','Last active':'Yesterday',Status:'Active'},{Name:'Emma Taylor',Role:'Billing',Email:'billing@clubos.example','Last active':'21 Aug',Status:'Active'}]},
 monitoring:{title:'System Monitoring',subtitle:'Application, database and integration health.',metrics:[['Uptime','99.98%'],['API p95','182 ms'],['Errors (24h)','7'],['Queued jobs','12']],columns:['Service','Region','Latency','Last check','Status'],rows:[{Service:'ClubOS Web',Region:'Global',Latency:'96 ms','Last check':'Just now',Status:'Operational'},{Service:'Supabase Database',Region:'AP Southeast',Latency:'124 ms','Last check':'Just now',Status:'Operational'},{Service:'Stripe Webhooks',Region:'Global',Latency:'211 ms','Last check':'1 min ago',Status:'Operational'},{Service:'Email Delivery',Region:'AU/NZ',Latency:'480 ms','Last check':'2 min ago',Status:'Degraded'}]},
 reports:{title:'Reports',subtitle:'Platform commercial and customer analytics.',metrics:[['ARR','$16.1k'],['Churn','1.8%'],['Active orgs','10'],['Total members','3,842']],columns:['Report','Period','Result','Generated','Status'],rows:[{Report:'MRR & ARR',Period:'Aug 2026',Result:'$1,338 MRR',Generated:'Today',Status:'Ready'},{Report:'Organisation Growth',Period:'Last 12 months',Result:'+8 organisations',Generated:'Today',Status:'Ready'},{Report:'Module Adoption',Period:'Aug 2026',Result:'Events 83%',Generated:'Yesterday',Status:'Ready'}]},
 settings:{title:'Platform Settings',subtitle:'Global defaults and integration configuration.',metrics:[['Environment','Production'],['Default currency','NZD'],['Email provider','Configured'],['Payments','Stripe ready']],columns:['Setting','Value','Scope','Updated','Status'],rows:[{Setting:'Platform name',Value:'ClubOS',Scope:'Global',Updated:'1 Aug 2026',Status:'Configured'},{Setting:'Default timezone',Value:'Pacific/Auckland',Scope:'New tenants',Updated:'1 Aug 2026',Status:'Configured'},{Setting:'Stripe',Value:'Connected',Scope:'Payments',Updated:'20 Aug 2026',Status:'Configured'},{Setting:'POLi',Value:'Sandbox / demo',Scope:'Payments',Updated:'20 Aug 2026',Status:'Testing'}]}
};
type PersistedRow={id:string;data:Row};
export function PlatformDemoPage({kind}:{kind:keyof typeof data}){
 const cfg=data[kind];const[q,setQ]=useState('');const[rows,setRows]=useState<PersistedRow[]>([]);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[editing,setEditing]=useState<PersistedRow|null>(null);const[form,setForm]=useState<Row>({});const[saving,setSaving]=useState(false);const[error,setError]=useState('');
 const load=async()=>{setLoading(true);const{data:db,error}=await supabase.from('module_records').select('id,data').is('organisation_id',null).eq('module_key',`platform:${kind}`).order('created_at');if(!error&&db){if(db.length===0&&cfg.rows.length){const seed=cfg.rows.map(row=>({organisation_id:null,module_key:`platform:${kind}`,scope:'platform',data:row}));const{data:created,error:seedError}=await supabase.from('module_records').insert(seed).select('id,data');if(!seedError&&created)setRows(created.map((r:any)=>({id:r.id,data:r.data as Row})));else setRows(cfg.rows.map((data,i)=>({id:`local-${i}`,data})))}else setRows(db.map((r:any)=>({id:r.id,data:r.data as Row})))}setLoading(false)};useEffect(()=>{load()},[kind]);
 const shown=useMemo(()=>rows.filter(r=>Object.values(r.data).some(v=>String(v).toLowerCase().includes(q.toLowerCase()))),[rows,q]);const begin=(r?:PersistedRow)=>{setEditing(r??null);setForm(r?{...r.data}:Object.fromEntries(cfg.columns.map((c,i)=>[c,i===cfg.columns.length-1?'Draft':''])));setError('');setOpen(true)};
 const save=async()=>{setSaving(true);try{if(editing&&!editing.id.startsWith('local-')){const{error}=await supabase.from('module_records').update({data:form,updated_at:new Date().toISOString()}).eq('id',editing.id);if(error)throw error}else{const{error}=await supabase.from('module_records').insert({organisation_id:null,module_key:`platform:${kind}`,scope:'platform',data:form});if(error)throw error}setOpen(false);notifySuccess(editing?'Changes saved successfully.':'Record created successfully.');await load()}catch(e:any){setError(e?.message??'Unable to save')}finally{setSaving(false)}};
 const remove=async(id:string)=>{if(!confirm('Delete this record?'))return;if(id.startsWith('local-')){setRows(r=>r.filter(x=>x.id!==id));return}const{error}=await supabase.from('module_records').delete().eq('id',id);if(error)alert(error.message);else load()};const exportCsv=()=>{const esc=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=[cfg.columns.map(esc).join(','),...shown.map(r=>cfg.columns.map(c=>esc(r.data[c])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`clubos-platform-${String(kind)}.csv`;a.click();URL.revokeObjectURL(a.href)};
 return <div className="space-y-6"><div className="flex items-end justify-between gap-3"><div><h1 className="text-2xl font-bold text-slate-900">{cfg.title}</h1><p className="mt-1 text-sm text-slate-500">{cfg.subtitle}</p></div><div className="flex gap-2"><button onClick={()=>begin()} className="inline-flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2 text-sm font-medium text-white"><Plus className="h-4 w-4"/>Add Record</button><button onClick={exportCsv} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><Download className="h-4 w-4"/>Export</button></div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cfg.metrics.map(([l,v])=><div key={l} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-medium uppercase tracking-wide text-slate-400">{l}</p><p className="mt-1 text-2xl font-semibold">{v}</p></div>)}</div><div className="rounded-xl border border-slate-200 bg-white overflow-hidden"><div className="p-4 border-b"><div className="relative max-w-md"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-sm" placeholder="Search records…"/></div></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{cfg.columns.map(c=><th key={c} className="px-4 py-3">{c}</th>)}<th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y">{loading?<tr><td colSpan={cfg.columns.length+1} className="p-6 text-center">Loading…</td></tr>:shown.length===0?<tr><td colSpan={cfg.columns.length+1} className="p-6 text-center text-slate-500">No records yet.</td></tr>:shown.map(r=><tr key={r.id}>{cfg.columns.map(c=><td key={c} className="whitespace-nowrap px-4 py-3 text-slate-700">{String(r.data[c]??'—')}</td>)}<td className="px-4 py-3"><div className="flex gap-2"><button onClick={()=>begin(r)}><Pencil className="h-4 w-4"/></button><button onClick={()=>remove(r.id)} className="text-red-500"><Trash2 className="h-4 w-4"/></button></div></td></tr>)}</tbody></table></div></div><Modal open={open} onClose={()=>setOpen(false)} title={editing?`Edit ${cfg.title}`:`Add ${cfg.title} Record`} size="lg" footer={<><button onClick={()=>setOpen(false)} className="btn-secondary">Cancel</button><button onClick={save} disabled={saving} className="btn-primary">{saving?'Saving…':'Save'}</button></>}><div className="grid gap-4 md:grid-cols-2">{error&&<div className="md:col-span-2 rounded bg-red-50 p-3 text-sm text-red-700">{error}</div>}{cfg.columns.map(c=><label key={c}><span className="label">{c}</span><input className="input" value={String(form[c]??'')} onChange={e=>setForm(f=>({...f,[c]:e.target.value}))}/></label>)}</div></Modal></div>}
