import { useEffect, useState } from 'react';
import { Save } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Fee={id?:string;name:string;enabled:boolean;fixed_amount:number;percentage:number;currency:string;minimum_fee:number|null;maximum_fee:number|null;active:boolean};
export function PlatformFeeSettings(){const[fee,setFee]=useState<Fee>({name:'Default platform transaction fee',enabled:false,fixed_amount:0,percentage:0,currency:'NZD',minimum_fee:null,maximum_fee:null,active:true});const[saving,setSaving]=useState(false);const[msg,setMsg]=useState('');
 useEffect(()=>{(async()=>{const{data}=await supabase.from('platform_transaction_fee_settings').select('*').eq('active',true).order('effective_from',{ascending:false}).limit(1).maybeSingle();if(data)setFee(data as Fee)})()},[]);
 const save=async()=>{setSaving(true);setMsg('');const payload={...fee,updated_at:new Date().toISOString()};const q=fee.id?supabase.from('platform_transaction_fee_settings').update(payload).eq('id',fee.id):supabase.from('platform_transaction_fee_settings').insert(payload);const{error}=await q;setSaving(false);setMsg(error?error.message:'Platform transaction fee saved.');};
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Platform Transaction Fees</h1><p className="mt-1 text-sm text-slate-500">Configure the additional ClubOS fee that can be applied to eligible transactions. Organisations separately choose whether members or the club absorb fees.</p></div><div className="card max-w-3xl p-6 space-y-5"><label className="flex items-center gap-3"><input type="checkbox" checked={fee.enabled} onChange={e=>setFee(f=>({...f,enabled:e.target.checked}))}/><span className="font-medium">Enable ClubOS transaction fee</span></label><div className="grid gap-4 md:grid-cols-2"><label><span className="label">Fixed amount per transaction</span><input className="input" type="number" min="0" step="0.01" value={fee.fixed_amount} onChange={e=>setFee(f=>({...f,fixed_amount:Number(e.target.value)||0}))}/></label><label><span className="label">Percentage fee (%)</span><input className="input" type="number" min="0" step="0.01" value={fee.percentage} onChange={e=>setFee(f=>({...f,percentage:Number(e.target.value)||0}))}/></label><label><span className="label">Minimum fee (optional)</span><input className="input" type="number" min="0" step="0.01" value={fee.minimum_fee??''} onChange={e=>setFee(f=>({...f,minimum_fee:e.target.value===''?null:Number(e.target.value)}))}/></label><label><span className="label">Maximum fee (optional)</span><input className="input" type="number" min="0" step="0.01" value={fee.maximum_fee??''} onChange={e=>setFee(f=>({...f,maximum_fee:e.target.value===''?null:Number(e.target.value)}))}/></label><label><span className="label">Currency</span><select className="input" value={fee.currency} onChange={e=>setFee(f=>({...f,currency:e.target.value}))}><option>NZD</option><option>AUD</option><option>USD</option></select></label></div><div className="rounded-lg bg-slate-50 p-4 text-sm text-slate-600">Example on a $100 transaction: <strong>${(Number(fee.fixed_amount||0)+100*Number(fee.percentage||0)/100).toFixed(2)}</strong> ClubOS fee before any minimum/maximum cap.</div><button onClick={save} disabled={saving} className="btn-primary inline-flex items-center gap-2"><Save className="h-4 w-4"/>{saving?'Saving…':'Save platform fee'}</button>{msg&&<p className="text-sm text-slate-600">{msg}</p>}</div></div>}
