import { FormEvent, useEffect, useMemo, useState } from 'react';
import { CalendarDays, CheckCircle2, MapPin, Ticket } from 'lucide-react';
import { useParams } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { formatCurrency } from '@/lib/utils';

type TicketType={id:string;name:string;description:string|null;price:number;quantity_available:number|null;max_per_order:number};
type EventData={id:string;title:string;description:string|null;venue:string|null;address:string|null;start_at:string;end_at:string|null;banner_url:string|null;currency:string;organisation_name:string;ticket_types:TicketType[]};

export function PublicEvent(){
 const {slug}=useParams(); const [event,setEvent]=useState<EventData|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [qty,setQty]=useState<Record<string,number>>({}); const [saving,setSaving]=useState(false); const [confirmation,setConfirmation]=useState<any>(null);
 useEffect(()=>{if(!slug)return;supabase.rpc('get_public_event',{p_slug:slug}).then(({data,error})=>{if(error)setError(error.message);else setEvent((Array.isArray(data)?data[0]:data) as EventData);setLoading(false);});},[slug]);
 const total=useMemo(()=>event?.ticket_types.reduce((sum,t)=>sum+(qty[t.id]||0)*Number(t.price),0)??0,[event,qty]);
 async function submit(e:FormEvent){e.preventDefault();if(!event)return;const items=event.ticket_types.map(t=>({ticket_type_id:t.id,quantity:qty[t.id]||0})).filter(x=>x.quantity>0);if(!items.length){setError('Select at least one ticket.');return;}setSaving(true);setError('');const {data,error}=await supabase.rpc('create_public_event_order',{p_event_id:event.id,p_purchaser_name:name,p_purchaser_email:email,p_items:items});if(error)setError(error.message);else setConfirmation(data);setSaving(false);}
 if(loading)return <div className="mx-auto max-w-3xl p-6"><div className="h-72 animate-pulse rounded-2xl bg-slate-100"/></div>;
 if(error&&!event)return <div className="mx-auto max-w-xl p-6"><div className="rounded-xl border bg-white p-8 text-center"><h1 className="text-xl font-bold">Event unavailable</h1><p className="mt-2 text-sm text-slate-500">{error}</p></div></div>;
 if(!event)return null;
 return <main className="min-h-screen bg-slate-50 pb-12"><div className="mx-auto max-w-4xl px-4 py-8">{event.banner_url&&<img src={event.banner_url} alt={`${event.title} banner`} className="h-56 w-full rounded-2xl object-cover sm:h-80"/>}<div className="mt-6 rounded-2xl bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-primary-700">{event.organisation_name}</p><h1 className="mt-1 text-3xl font-bold text-slate-900">{event.title}</h1>{event.description&&<p className="mt-3 text-slate-600">{event.description}</p>}<div className="mt-5 grid gap-3 text-sm text-slate-600 sm:grid-cols-2"><p className="flex gap-2"><CalendarDays className="h-5 w-5"/>{new Date(event.start_at).toLocaleString()}</p><p className="flex gap-2"><MapPin className="h-5 w-5"/>{event.venue||'Venue TBC'}{event.address?` · ${event.address}`:''}</p></div></div>
 {confirmation?<div className="mt-6 rounded-2xl bg-white p-8 text-center shadow-sm"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-600"/><h2 className="mt-3 text-2xl font-bold">Order received</h2><p className="mt-2 text-slate-600">Reference: <span className="font-mono">{confirmation.order_id}</span></p><p className="mt-2 text-sm text-slate-500">{confirmation.payment_status==='free'?'Your free tickets have been created.':'This order is pending payment. Once Stripe/POLi is connected, the live payment step will complete here.'}</p></div>:
 <form onSubmit={submit} className="mt-6 rounded-2xl bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Ticket className="h-5 w-5 text-primary-700"/><h2 className="text-xl font-bold">Tickets</h2></div><div className="mt-4 space-y-3">{event.ticket_types.map(t=><div key={t.id} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{t.name}</p>{t.description&&<p className="text-sm text-slate-500">{t.description}</p>}<p className="mt-1 text-sm font-medium">{Number(t.price)===0?'Free':formatCurrency(Number(t.price),event.currency)}</p></div><label className="flex items-center gap-2 text-sm">Qty <select className="input w-24" value={qty[t.id]||0} onChange={e=>setQty(v=>({...v,[t.id]:Number(e.target.value)}))}>{Array.from({length:Math.min(t.max_per_order||10,10)+1},(_,i)=><option key={i} value={i}>{i}</option>)}</select></label></div>)}</div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Purchaser name<input required className="input mt-2 w-full" value={name} onChange={e=>setName(e.target.value)}/></label><label className="text-sm font-medium">Email<input required type="email" className="input mt-2 w-full" value={email} onChange={e=>setEmail(e.target.value)}/></label></div>{error&&<div className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="mt-6 flex flex-col gap-3 border-t pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-lg font-bold">Total: {formatCurrency(total,event.currency)}</p><button disabled={saving||total<0} className="btn-primary">{saving?'Submitting…':total===0?'Get tickets':'Continue to payment'}</button></div></form>}
 </div></main>;
}
