import { useEffect, useMemo, useState } from 'react';
import { Search, Plus, Download, Pencil, Trash2 } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import { Modal } from '@/components/ui/Modal';

type Row = Record<string, string | number>;
interface Config { title:string; subtitle:string; metrics:[string,string][]; columns:string[]; rows:Row[] }

const common = {
  sports: { title:'Sports', subtitle:'Manage sporting programmes and seasons.', metrics:[['Active sports','4'],['Teams','9'],['Participants','128'],['Upcoming fixtures','7']], columns:['Sport','Season','Teams','Participants','Status'], rows:[
    {Sport:'Cricket',Season:'2026/27',Teams:4,Participants:62,Status:'Active'},{Sport:'Netball',Season:'2026',Teams:2,Participants:27,Status:'Active'},{Sport:'Football',Season:'2026',Teams:2,Participants:31,Status:'Active'},{Sport:'Badminton',Season:'2026',Teams:1,Participants:8,Status:'Planning'}]},
  finance: { title:'Finance Dashboard', subtitle:'Membership, events, merchandise and donation income.', metrics:[['Income YTD','$38,460'],['Outstanding','$3,280'],['This month','$6,945'],['Refunds','$420']], columns:['Category','This month','YTD','Outstanding','Status'], rows:[
    {Category:'Membership fees','This month':'$3,420',YTD:'$19,840',Outstanding:'$2,180',Status:'Healthy'},{Category:'Event tickets','This month':'$2,210',YTD:'$9,650',Outstanding:'$0',Status:'Healthy'},{Category:'Merchandise','This month':'$735',YTD:'$4,970',Outstanding:'$320',Status:'Healthy'},{Category:'Donations','This month':'$580',YTD:'$4,000',Outstanding:'$780',Status:'Follow-up'}]},
  transactions: { title:'Transactions', subtitle:'Sample payment history across all payment channels.', metrics:[['Transactions','86'],['Paid','79'],['Pending','5'],['Failed','2']], columns:['Reference','Member','Type','Method','Amount','Status'], rows:[
    {Reference:'PAY-1042',Member:'James Wilson',Type:'Membership',Method:'Stripe','$ Amount':'$220',Amount:'$220',Status:'Paid'},{Reference:'PAY-1041',Member:'Sarah Connors',Type:'Event ticket',Method:'POLi',Amount:'$85',Status:'Paid'},{Reference:'PAY-1039',Member:'Michael Chen',Type:'Merchandise',Method:'Card',Amount:'$65',Status:'Paid'},{Reference:'PAY-1038',Member:'Robert Jones',Type:'Membership',Method:'Bank transfer',Amount:'$220',Status:'Pending'}]},
  communications: { title:'Communications', subtitle:'Email campaigns and member notifications.', metrics:[['Sent this month','1,248'],['Open rate','68%'],['Queued','42'],['Failed','6']], columns:['Campaign','Audience','Sent','Opened','Status'], rows:[
    {Campaign:'AGM Notice 2026',Audience:'Voting members',Sent:112,Opened:'82%',Status:'Sent'},{Campaign:'Awards Night Tickets',Audience:'All members',Sent:158,Opened:'74%',Status:'Sent'},{Campaign:'Membership Renewal Reminder',Audience:'Expiring members',Sent:38,Opened:'61%',Status:'Sent'},{Campaign:'Junior Training Update',Audience:'Junior parents',Sent:46,Opened:'-',Status:'Draft'}]},
  send: { title:'Send Email', subtitle:'Compose a test communication to a member segment.', metrics:[['Recipients available','158'],['Segments','8'],['Templates','6'],['Scheduled','2']], columns:['Template','Subject','Audience','Last used','Status'], rows:[
    {Template:'Membership Renewal',Subject:'Your membership is due for renewal',Audience:'Expiring members','Last used':'18 Aug 2026',Status:'Ready'},{Template:'Event Invitation',Subject:'You’re invited to our next club event',Audience:'All members','Last used':'12 Aug 2026',Status:'Ready'},{Template:'Committee Update',Subject:'Update from your committee',Audience:'Members','Last used':'1 Aug 2026',Status:'Ready'}]},
  history: { title:'Communication History', subtitle:'Audit trail of emails and notices sent by the club.', metrics:[['Last 30 days','14'],['Recipients','2,106'],['Bounced','11'],['Unsubscribed','3']], columns:['Date','Campaign','Sent by','Recipients','Status'], rows:[
    {Date:'22 Aug 2026',Campaign:'Awards Night Tickets','Sent by':'Sarah Connors',Recipients:158,Status:'Delivered'},{Date:'18 Aug 2026',Campaign:'Renewal Reminder','Sent by':'Sarah Connors',Recipients:38,Status:'Delivered'},{Date:'10 Aug 2026',Campaign:'AGM Notice','Sent by':'James Wilson',Recipients:112,Status:'Delivered'}]},
  governance: { title:'Governance Dashboard', subtitle:'Committee, meetings, motions and governance actions.', metrics:[['Committee members','8'],['Open motions','2'],['Actions due','5'],['Next meeting','3 Sep']], columns:['Item','Type','Owner','Due','Status'], rows:[
    {Item:'Approve 2026/27 budget',Type:'Motion',Owner:'Treasurer',Due:'3 Sep 2026',Status:'Open'},{Item:'Review member protection policy',Type:'Action',Owner:'Secretary',Due:'15 Sep 2026',Status:'In progress'},{Item:'Equipment purchase approval',Type:'Motion',Owner:'Committee',Due:'3 Sep 2026',Status:'Open'}]},
  committee: { title:'Committee', subtitle:'Current committee and office holders.', metrics:[['Officers','3'],['Committee','8'],['Vacancies','1'],['Term','2026/27']], columns:['Name','Position','Email','Term','Status'], rows:[
    {Name:'James Wilson',Position:'President',Email:'james.wilson@example.com',Term:'2026/27',Status:'Active'},{Name:'Sarah Connors',Position:'Secretary',Email:'sarah.connors@example.com',Term:'2026/27',Status:'Active'},{Name:'Robert Jones',Position:'Treasurer',Email:'robert.jones@example.com',Term:'2026/27',Status:'Active'},{Name:'Emily Patel',Position:'Committee Member',Email:'emily.patel@example.com',Term:'2026/27',Status:'Active'}]},
  motions: { title:'Motions', subtitle:'Track proposed, approved and declined club motions.', metrics:[['Open','2'],['Passed YTD','11'],['Declined','1'],['Awaiting vote','1']], columns:['Motion','Proposed by','Meeting','Result','Status'], rows:[
    {Motion:'Approve $500 club management system budget','Proposed by':'Sarah Connors',Meeting:'AGM 21 Aug 2026',Result:'Passed',Status:'Approved'},{Motion:'Purchase new junior cricket wickets','Proposed by':'David Thompson',Meeting:'Committee 3 Sep',Result:'-',Status:'Open'},{Motion:'Increase senior subscription to $230','Proposed by':'Robert Jones',Meeting:'Committee 3 Sep',Result:'-',Status:'Open'}]},
  documents: { title:'Documents', subtitle:'Policies, constitution, minutes and club records.', metrics:[['Documents','24'],['Policies','9'],['Awaiting review','3'],['Expiring','1']], columns:['Document','Category','Version','Review date','Status'], rows:[
    {Document:'Club Constitution 2026',Category:'Governance',Version:'2.0','Review date':'21 Aug 2029',Status:'Current'},{Document:'Member Protection Policy',Category:'Policy',Version:'1.4','Review date':'15 Sep 2026',Status:'Review due'},{Document:'AGM Minutes 2026',Category:'Minutes',Version:'Final','Review date':'-',Status:'Current'},{Document:'Privacy Policy',Category:'Compliance',Version:'1.2','Review date':'1 Mar 2027',Status:'Current'}]},
  merchandise: { title:'Merchandise', subtitle:'Products, stock and member orders.', metrics:[['Products','8'],['Orders this month','17'],['Sales','$1,265'],['Low stock','2']], columns:['Product','SKU','Price','Stock','Status'], rows:[
    {Product:'Club Playing Shirt',SKU:'CLS-SHIRT',Price:'$55',Stock:24,Status:'Active'},{Product:'Club Cap',SKU:'CLS-CAP',Price:'$25',Stock:9,Status:'Low stock'},{Product:'Training Hoodie',SKU:'CLS-HOOD',Price:'$70',Stock:18,Status:'Active'},{Product:'Junior Training Tee',SKU:'CLS-JTEE',Price:'$35',Stock:6,Status:'Low stock'}]},
  donations: { title:'Donations', subtitle:'Donor records, campaigns and receipts.', metrics:[['YTD donations','$4,000'],['Donors','31'],['Campaigns','3'],['Recurring','7']], columns:['Donor','Campaign','Amount','Date','Status'], rows:[
    {Donor:'A. Perera',Campaign:'Junior Equipment Fund',Amount:'$500',Date:'20 Aug 2026',Status:'Received'},{Donor:'James Wilson',Campaign:'Club Development',Amount:'$250',Date:'14 Aug 2026',Status:'Received'},{Donor:'Local Business Sponsor',Campaign:'Junior Equipment Fund',Amount:'$1,000',Date:'5 Aug 2026',Status:'Received'}]},
  contacts: { title:'Organisations & Contacts', subtitle:'Sponsors, suppliers, venues and community contacts.', metrics:[['Contacts','42'],['Sponsors','8'],['Suppliers','11'],['Venues','6']], columns:['Organisation','Contact','Category','Phone','Status'], rows:[
    {Organisation:'Wellington Sports Centre',Contact:'Venue Manager',Category:'Venue',Phone:'04 555 2100',Status:'Active'},{Organisation:'Cricket Supplies NZ',Contact:'Matt Green',Category:'Supplier',Phone:'04 555 3900',Status:'Active'},{Organisation:'Community Trust',Contact:'Grants Team',Category:'Funder',Phone:'04 555 4800',Status:'Active'},{Organisation:'Metro Accounting',Contact:'Lisa Kumar',Category:'Professional services',Phone:'04 555 1500',Status:'Active'}]},
  contracts: { title:'Contracts', subtitle:'Supplier, venue, sponsor and service agreements.', metrics:[['Active contracts','12'],['Value','$26,400'],['Renewing soon','3'],['Expired','1']], columns:['Contract','Party','Start','Expiry','Status'], rows:[
    {Contract:'Ground Hire Agreement',Party:'Wellington Sports Centre',Start:'1 Sep 2025',Expiry:'31 Aug 2027',Status:'Active'},{Contract:'Uniform Supply',Party:'Cricket Supplies NZ',Start:'1 Jan 2026',Expiry:'31 Dec 2026',Status:'Renewal due'},{Contract:'Website Hosting',Party:'Netlify',Start:'1 Jul 2026',Expiry:'30 Jun 2027',Status:'Active'}]},
  tasks: { title:'Tasks & Compliance', subtitle:'Operational tasks, owners and due dates.', metrics:[['Open tasks','18'],['Overdue','3'],['Due this week','6'],['Completed this month','24']], columns:['Task','Owner','Area','Due','Status'], rows:[
    {Task:'Update member register after AGM',Owner:'Secretary',Area:'Governance',Due:'28 Aug 2026',Status:'In progress'},{Task:'Submit annual return',Owner:'Secretary',Area:'Compliance',Due:'30 Sep 2026',Status:'Open'},{Task:'Review first aid kits',Owner:'Team Manager',Area:'Health & Safety',Due:'26 Aug 2026',Status:'Overdue'},{Task:'Reconcile event ticket sales',Owner:'Treasurer',Area:'Finance',Due:'25 Aug 2026',Status:'Open'}]},
  privacy: { title:'Privacy & Data Governance', subtitle:'Consent, retention and privacy request monitoring.', metrics:[['Consent coverage','96%'],['Open requests','1'],['Records due deletion','4'],['Last audit','12 Aug']], columns:['Record','Type','Owner','Due','Status'], rows:[
    {Record:'PR-0007 Sarah Connors',Type:'Access request',Owner:'Privacy Officer',Due:'4 Sep 2026',Status:'Open'},{Record:'Junior photo consent review',Type:'Consent',Owner:'Secretary',Due:'31 Aug 2026',Status:'In progress'},{Record:'Inactive member retention batch',Type:'Retention',Owner:'System',Due:'1 Sep 2026',Status:'Scheduled'}]},
  compliance: { title:'Regulatory Compliance', subtitle:'Club compliance register and statutory obligations.', metrics:[['Obligations','16'],['Compliant','14'],['Due soon','2'],['Overdue','0']], columns:['Requirement','Authority','Owner','Due','Status'], rows:[
    {Requirement:'Incorporated society annual return',Authority:'Companies Office',Owner:'Secretary',Due:'30 Sep 2026',Status:'Due soon'},{Requirement:'Financial statements approval',Authority:'Club Constitution',Owner:'Treasurer',Due:'21 Aug 2026',Status:'Complete'},{Requirement:'Health & safety review',Authority:'Club Policy',Owner:'President',Due:'1 Oct 2026',Status:'Current'}]},
  reports: { title:'Reports & Analytics', subtitle:'Operational and membership insights.', metrics:[['Active members','148'],['Retention','91%'],['Revenue YTD','$38.5k'],['Event attendance','73%']], columns:['Report','Period','Key result','Generated','Status'], rows:[
    {Report:'Membership Summary',Period:'2026/27','Key result':'148 active members',Generated:'24 Aug 2026',Status:'Ready'},{Report:'Financial Summary',Period:'YTD','Key result':'$38,460 income',Generated:'24 Aug 2026',Status:'Ready'},{Report:'Event Performance',Period:'Last 12 months','Key result':'73% avg attendance',Generated:'23 Aug 2026',Status:'Ready'}]},
  clubsettings: { title:'Club Details', subtitle:'Core organisation settings and operating information.', metrics:[['Profile completion','100%'],['Currency','NZD'],['Timezone','Auckland'],['Financial year','Sep–Aug']], columns:['Setting','Value','Last updated','Owner','Status'], rows:[
    {Setting:'Legal name',Value:'Demo Sports Club Incorporated','Last updated':'21 Aug 2026',Owner:'Secretary',Status:'Configured'},{Setting:'Trading name',Value:'Demo Sports Club','Last updated':'21 Aug 2026',Owner:'Secretary',Status:'Configured'},{Setting:'Membership year',Value:'1 Sep – 31 Aug','Last updated':'21 Aug 2026',Owner:'Committee',Status:'Configured'}]},
  branding: { title:'Branding', subtitle:'Club identity used across member portals and communications.', metrics:[['Logo','Configured'],['Primary colour','#2563EB'],['Email header','Configured'],['Portal banner','Configured']], columns:['Asset','Value','Usage','Updated','Status'], rows:[
    {Asset:'Primary logo',Value:'Demo Sports Club shield',Usage:'Portal + email',Updated:'1 Aug 2026',Status:'Active'},{Asset:'Primary colour',Value:'#2563EB',Usage:'Buttons + navigation',Updated:'1 Aug 2026',Status:'Active'},{Asset:'Email footer',Value:'Club contact + privacy notice',Usage:'Outgoing email',Updated:'5 Aug 2026',Status:'Active'}]},
  users: { title:'Users', subtitle:'Club administrator accounts and access status.', metrics:[['Admin users','5'],['Full access','1'],['Read only','1'],['Invites pending','1']], columns:['User','Role','Email','Last login','Status'], rows:[
    {User:'James Wilson',Role:'Organisation Owner',Email:'owner@demosportsclub.example','Last login':'Today',Status:'Active'},{User:'Sarah Connors',Role:'Secretary',Email:'secretary@demosportsclub.example','Last login':'Yesterday',Status:'Active'},{User:'Robert Jones',Role:'Treasurer',Email:'treasurer@demosportsclub.example','Last login':'22 Aug',Status:'Active'},{User:'Helen Taylor',Role:'Read Only Administrator',Email:'readonly@demosportsclub.example','Last login':'18 Aug',Status:'Active'}]},
  roles: { title:'Roles', subtitle:'Role-based access profiles for club administrators.', metrics:[['Roles','6'],['Custom roles','1'],['Permission rules','74'],['Overrides','2']], columns:['Role','Users','Access','Modules','Status'], rows:[
    {Role:'Organisation Owner',Users:1,Access:'Full',Modules:'All',Status:'Active'},{Role:'Secretary',Users:1,Access:'Custom',Modules:'Membership, Governance, Communications',Status:'Active'},{Role:'Treasurer',Users:1,Access:'Custom',Modules:'Finance + Member View',Status:'Active'},{Role:'Team Manager',Users:1,Access:'Custom',Modules:'Teams + Events',Status:'Active'},{Role:'Read Only Administrator',Users:1,Access:'Read only',Modules:'Enabled modules',Status:'Active'}]},
  modules: { title:'Modules', subtitle:'Enable or disable ClubOS modules for this organisation.', metrics:[['Enabled','14'],['Core','4'],['Optional','10'],['Disabled','1']], columns:['Module','Category','Access','Plan','Status'], rows:[
    {Module:'Membership',Category:'Core',Access:'Full',Plan:'Included',Status:'Enabled'},{Module:'Events & Ticketing',Category:'Operations',Access:'Full',Plan:'Included',Status:'Enabled'},{Module:'Merchandise',Category:'Commerce',Access:'Full',Plan:'Add-on',Status:'Enabled'},{Module:'Donations',Category:'Commerce',Access:'Full',Plan:'Add-on',Status:'Enabled'},{Module:'Contracts',Category:'Administration',Access:'Full',Plan:'Pro',Status:'Enabled'}]},
} satisfies Record<string, Config>;

type PersistedRow = { id:string; data:Row };

export function DemoModulePage({ kind }: { kind: keyof typeof common }) {
  const cfg = common[kind]; const { activeOrg } = useAuth();
  const [query,setQuery] = useState(''); const [rows,setRows] = useState<PersistedRow[]>([]); const [loading,setLoading] = useState(true);
  const [open,setOpen] = useState(false); const [editing,setEditing] = useState<PersistedRow|null>(null); const [form,setForm] = useState<Row>({}); const [saving,setSaving] = useState(false); const [error,setError] = useState('');
  const load = async () => { if (!activeOrg) return; setLoading(true); const {data,error} = await supabase.from('module_records').select('id,data').eq('organisation_id',activeOrg.id).eq('module_key',kind).order('created_at'); if (!error && data) { if (data.length === 0 && cfg.rows.length > 0) { const seed=cfg.rows.map(row=>({organisation_id:activeOrg.id,module_key:kind,scope:'organisation',data:row})); const {data:created,error:seedError}=await supabase.from('module_records').insert(seed).select('id,data'); if(!seedError&&created)setRows(created.map((r:any)=>({id:r.id,data:r.data as Row}))); else setRows(cfg.rows.map((data,i)=>({id:`local-${i}`,data}))); } else setRows(data.map((r:any)=>({id:r.id,data:r.data as Row}))); } setLoading(false); };
  useEffect(()=>{load();},[activeOrg,kind]);
  const filtered = useMemo(()=> rows.filter(r => Object.values(r.data).some(v=>String(v).toLowerCase().includes(query.toLowerCase()))),[rows,query]);
  const beginAdd=()=>{setEditing(null);setForm(Object.fromEntries(cfg.columns.map((c,i)=>[c,i===cfg.columns.length-1?'Draft':''])));setError('');setOpen(true)};
  const beginEdit=(row:PersistedRow)=>{setEditing(row);setForm({...row.data});setError('');setOpen(true)};
  const save=async()=>{ if(!activeOrg)return; setSaving(true);setError(''); try { if(editing && !editing.id.startsWith('local-')){ const {error}=await supabase.from('module_records').update({data:form,updated_at:new Date().toISOString()}).eq('id',editing.id); if(error)throw error; } else { const {error}=await supabase.from('module_records').insert({organisation_id:activeOrg.id,module_key:kind,scope:'organisation',data:form}); if(error)throw error; } setOpen(false);await load(); } catch(e:any){setError(e?.message??'Unable to save record')} finally{setSaving(false)} };
  const remove=async(id:string)=>{if(!confirm('Delete this record?'))return;if(id.startsWith('local-')){setRows(r=>r.filter(x=>x.id!==id));return;}const {error}=await supabase.from('module_records').delete().eq('id',id);if(error)alert(error.message);else load();};
  const exportCsv=()=>{const esc=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=[cfg.columns.map(esc).join(','),...filtered.map(r=>cfg.columns.map(c=>esc(r.data[c])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`clubos-${String(kind)}.csv`;a.click();URL.revokeObjectURL(a.href)};
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold text-slate-900">{cfg.title}</h1><p className="mt-1 text-sm text-slate-500">{cfg.subtitle}</p></div><div className="flex gap-2"><button onClick={beginAdd} className="inline-flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2 text-sm font-medium text-white"><Plus className="h-4 w-4"/>Add Record</button><button onClick={exportCsv} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><Download className="h-4 w-4"/>Export</button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cfg.metrics.map(([l,v])=><div key={l} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-medium uppercase tracking-wide text-slate-400">{l}</p><p className="mt-1 text-2xl font-semibold text-slate-900">{v}</p></div>)}</div>
    <div className="rounded-xl border border-slate-200 bg-white overflow-hidden"><div className="border-b border-slate-200 p-4"><div className="relative max-w-md"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search records…" className="w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none focus:border-primary-500"/></div></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{cfg.columns.map(c=><th className="px-4 py-3" key={c}>{c}</th>)}<th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{loading?<tr><td colSpan={cfg.columns.length+1} className="p-6 text-center text-slate-500">Loading…</td></tr>:filtered.length===0?<tr><td colSpan={cfg.columns.length+1} className="p-6 text-center text-slate-500">No records yet. Click Add Record.</td></tr>:filtered.map(r=><tr key={r.id} className="hover:bg-slate-50">{cfg.columns.map(c=><td className="whitespace-nowrap px-4 py-3 text-slate-700" key={c}>{String(r.data[c] ?? '—')}</td>)}<td className="px-4 py-3"><div className="flex gap-2"><button onClick={()=>beginEdit(r)} className="rounded p-1 text-slate-500 hover:bg-slate-100"><Pencil className="h-4 w-4"/></button><button onClick={()=>remove(r.id)} className="rounded p-1 text-slate-500 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4"/></button></div></td></tr>)}</tbody></table></div></div>
    <Modal open={open} onClose={()=>setOpen(false)} title={editing?`Edit ${cfg.title}`:`Add ${cfg.title} Record`} size="lg" footer={<><button onClick={()=>setOpen(false)} className="btn-secondary">Cancel</button><button onClick={save} disabled={saving} className="btn-primary">{saving?'Saving…':'Save'}</button></>}><div className="grid gap-4 md:grid-cols-2">{error&&<div className="md:col-span-2 rounded bg-red-50 p-3 text-sm text-red-700">{error}</div>}{cfg.columns.map(c=><label key={c} className="block"><span className="label">{c}</span><input className="input" value={String(form[c]??'')} onChange={e=>setForm(f=>({...f,[c]:e.target.value}))}/></label>)}</div></Modal>
    <p className="text-xs text-slate-400">Records on this screen are persisted to Supabase and can be added, edited, deleted and exported.</p></div>
}
