import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { CalendarDays, MapPin, Plus, QrCode, Ticket, Trash2 } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import { PageHeader } from '@/components/ui/PageHeader';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { Modal } from '@/components/ui/Modal';
import { FormField, Select, TextArea, TextInput } from '@/components/ui/FormField';
import { formatCurrency } from '@/lib/utils';
import { useOrganisationCurrency } from '@/lib/useOrganisationCurrency';

interface EventRow { id:string; title:string; description:string|null; venue:string|null; start_at:string; end_at:string|null; capacity:number|null; status:string; event_ticket_types?: { id:string; name:string; price:number; member_price:number|null; quantity_available:number|null }[]; event_tickets?: { id:string; status:string }[] }
const emptyForm={title:'',description:'',venue:'',address:'',start_at:'',end_at:'',capacity:'',status:'draft',ticket_name:'General Admission',price:'0',member_price:'',quantity_available:''};

export function EventsPage() {
  const { activeOrg, profile } = useAuth();
  const { currency } = useOrganisationCurrency();
  const [events,setEvents] = useState<EventRow[]>([]); const [loading,setLoading] = useState(true); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [form,setForm]=useState(emptyForm);
  const load=()=>{ if(!activeOrg)return; setLoading(true); supabase.from('events').select('*, event_ticket_types(*), event_tickets(id,status)').eq('organisation_id',activeOrg.id).order('start_at').then(({data})=>{setEvents((data??[]) as EventRow[]);setLoading(false);}); };
  useEffect(load,[activeOrg]);
  const totalTickets=useMemo(()=>events.reduce((n,e)=>n+(e.event_tickets?.length??0),0),[events]); const set=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
  async function createEvent(e:FormEvent){ e.preventDefault(); if(!activeOrg)return; setSaving(true);setError('');try{
    const {data:event,error:evErr}=await supabase.from('events').insert({organisation_id:activeOrg.id,title:form.title,description:form.description||null,venue:form.venue||null,address:form.address||null,start_at:new Date(form.start_at).toISOString(),end_at:form.end_at?new Date(form.end_at).toISOString():null,capacity:form.capacity?Number(form.capacity):null,status:form.status,created_by:profile?.id??null}).select('id').single(); if(evErr)throw evErr;
    const {error:tErr}=await supabase.from('event_ticket_types').insert({organisation_id:activeOrg.id,event_id:event.id,name:form.ticket_name||'General Admission',price:Number(form.price||0),member_price:form.member_price?Number(form.member_price):null,quantity_available:form.quantity_available?Number(form.quantity_available):null}); if(tErr)throw tErr;
    setOpen(false);setForm(emptyForm);load();
  }catch(err:any){setError(err?.message??'Unable to create event');}finally{setSaving(false);}}
  async function removeEvent(id:string){ if(!confirm('Delete this event and its ticket setup?'))return; const {error}=await supabase.from('events').delete().eq('id',id); if(error)alert(error.message); else load(); }
  return <div className="space-y-6">
    <PageHeader title="Events & Ticketing" description={`${events.length} events · ${totalTickets} issued tickets`} actions={<div className="flex gap-2"><Link className="btn-secondary" to="/admin/events/checkin"><QrCode className="h-4 w-4"/> Check-in Scanner</Link><button className="btn-primary" onClick={()=>setOpen(true)}><Plus className="h-4 w-4"/> New Event</button></div>} />
    <div className="grid gap-4 md:grid-cols-3"><div className="card p-4"><p className="text-xs text-slate-500">Published</p><p className="mt-1 text-2xl font-bold">{events.filter(e=>e.status==='published').length}</p></div><div className="card p-4"><p className="text-xs text-slate-500">Tickets issued</p><p className="mt-1 text-2xl font-bold">{totalTickets}</p></div><div className="card p-4"><p className="text-xs text-slate-500">Checked in</p><p className="mt-1 text-2xl font-bold">{events.reduce((n,e)=>n+(e.event_tickets?.filter(t=>t.status==='used').length??0),0)}</p></div></div>
    {loading?<div className="card h-40 animate-pulse"/>:<div className="grid gap-4 lg:grid-cols-2">{events.map(e=><div key={e.id} className="card p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-primary-700"/><h3 className="font-semibold text-slate-900">{e.title}</h3></div><p className="mt-2 text-sm text-slate-500">{e.description}</p></div><div className="flex items-center gap-2"><StatusBadge status={e.status}/><button onClick={()=>removeEvent(e.id)} className="rounded p-1 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4"/></button></div></div><div className="mt-4 space-y-2 text-sm text-slate-600"><p>{new Date(e.start_at).toLocaleString('en-NZ',{dateStyle:'medium',timeStyle:'short'})}</p><p className="flex items-center gap-2"><MapPin className="h-4 w-4"/>{e.venue??'Venue TBC'}</p><p className="flex items-center gap-2"><Ticket className="h-4 w-4"/>{e.event_tickets?.length??0} issued · {e.capacity??'Unlimited'} capacity</p></div><div className="mt-4 border-t pt-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Ticket types</p><div className="mt-2 flex flex-wrap gap-2">{e.event_ticket_types?.map(t=><span key={t.id} className="rounded-full bg-slate-100 px-3 py-1 text-xs">{t.name}: {Number(t.price)===0?'Free':formatCurrency(Number(t.price), currency)}</span>)}</div></div></div>)}</div>}
    <Modal open={open} onClose={()=>setOpen(false)} title="Create Event" description="Create the event and its first ticket type." size="lg" footer={<><button onClick={()=>setOpen(false)} className="btn-secondary">Cancel</button><button form="event-form" disabled={saving} className="btn-primary">{saving?'Creating…':'Create Event'}</button></>}><form id="event-form" onSubmit={createEvent} className="space-y-4">{error&&<div className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="grid gap-4 md:grid-cols-2"><FormField label="Event title" required><TextInput required value={form.title} onChange={e=>set('title',e.target.value)}/></FormField><FormField label="Status"><Select value={form.status} onChange={e=>set('status',e.target.value)}><option value="draft">Draft</option><option value="published">Published</option></Select></FormField><FormField label="Start" required><TextInput required type="datetime-local" value={form.start_at} onChange={e=>set('start_at',e.target.value)}/></FormField><FormField label="End"><TextInput type="datetime-local" value={form.end_at} onChange={e=>set('end_at',e.target.value)}/></FormField><FormField label="Venue"><TextInput value={form.venue} onChange={e=>set('venue',e.target.value)}/></FormField><FormField label="Capacity"><TextInput type="number" min="0" value={form.capacity} onChange={e=>set('capacity',e.target.value)}/></FormField><FormField label="Address" className="md:col-span-2"><TextInput value={form.address} onChange={e=>set('address',e.target.value)}/></FormField><FormField label="Description" className="md:col-span-2"><TextArea value={form.description} onChange={e=>set('description',e.target.value)}/></FormField></div><div className="border-t pt-4"><h3 className="font-medium">Initial ticket type</h3><div className="mt-3 grid gap-4 md:grid-cols-2"><FormField label="Ticket name"><TextInput value={form.ticket_name} onChange={e=>set('ticket_name',e.target.value)}/></FormField><FormField label="Public price"><TextInput type="number" step="0.01" min="0" value={form.price} onChange={e=>set('price',e.target.value)}/></FormField><FormField label="Member price"><TextInput type="number" step="0.01" min="0" value={form.member_price} onChange={e=>set('member_price',e.target.value)}/></FormField><FormField label="Quantity available"><TextInput type="number" min="0" value={form.quantity_available} onChange={e=>set('quantity_available',e.target.value)}/></FormField></div></div></form></Modal>
  </div>;
}
