import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { CalendarDays, Copy, Edit3, Image as ImageIcon, Link as LinkIcon, MapPin, Plus, QrCode, Ticket, Trash2 } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import { PageHeader } from '@/components/ui/PageHeader';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { Modal } from '@/components/ui/Modal';
import { FormField, Select, TextArea, TextInput } from '@/components/ui/FormField';
import { formatCurrency } from '@/lib/utils';
import { useOrganisationCurrency } from '@/lib/useOrganisationCurrency';

type TicketType={id?:string;name:string;description:string;price:string;member_price:string;quantity_available:string;max_per_order:string;is_active:boolean};
interface EventRow { id:string; title:string; description:string|null; venue:string|null; address?:string|null; start_at:string; end_at:string|null; capacity:number|null; banner_url?:string|null; public_slug?:string|null; status:string; event_ticket_types?: any[]; event_tickets?: { id:string; status:string; ticket_type_id?:string }[] }
const newTicket=():TicketType=>({name:'General Admission',description:'',price:'0',member_price:'',quantity_available:'',max_per_order:'10',is_active:true});
const emptyForm=()=>({id:'',title:'',description:'',venue:'',address:'',start_at:'',end_at:'',capacity:'',status:'draft',banner_url:'',public_slug:'',tickets:[newTicket()] as TicketType[]});
const localDateTime=(iso?:string|null)=>iso?new Date(new Date(iso).getTime()-new Date(iso).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||'event';

export function EventsPage() {
  const { activeOrg, profile } = useAuth();
  const { currency } = useOrganisationCurrency();
  const [events,setEvents] = useState<EventRow[]>([]); const [loading,setLoading] = useState(true); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [form,setForm]=useState(emptyForm()); const [banner,setBanner]=useState<File|null>(null);
  const load=()=>{ if(!activeOrg)return; setLoading(true); supabase.from('events').select('*, event_ticket_types(*), event_tickets(id,status,ticket_type_id)').eq('organisation_id',activeOrg.id).order('start_at').then(({data,error})=>{if(error)setError(error.message);setEvents((data??[]) as EventRow[]);setLoading(false);}); };
  useEffect(load,[activeOrg?.id]);
  const totalTickets=useMemo(()=>events.reduce((n,e)=>n+(e.event_tickets?.length??0),0),[events]);
  const set=(k:string,v:any)=>setForm((f:any)=>({...f,[k]:v}));
  const setTicket=(i:number,k:keyof TicketType,v:any)=>setForm((f:any)=>({...f,tickets:f.tickets.map((t:TicketType,idx:number)=>idx===i?{...t,[k]:v}:t)}));
  function openNew(){setForm(emptyForm());setBanner(null);setError('');setMessage('');setOpen(true);}
  function openEdit(e:EventRow){setForm({id:e.id,title:e.title,description:e.description??'',venue:e.venue??'',address:e.address??'',start_at:localDateTime(e.start_at),end_at:localDateTime(e.end_at),capacity:e.capacity?.toString()??'',status:e.status,banner_url:e.banner_url??'',public_slug:e.public_slug??'',tickets:(e.event_ticket_types??[]).map((t:any)=>({id:t.id,name:t.name,description:t.description??'',price:String(t.price??0),member_price:t.member_price==null?'':String(t.member_price),quantity_available:t.quantity_available==null?'':String(t.quantity_available),max_per_order:String(t.max_per_order??10),is_active:t.is_active!==false}))}); if(!(e.event_ticket_types??[]).length)setForm((f:any)=>({...f,tickets:[newTicket()]}));setBanner(null);setError('');setMessage('');setOpen(true);}

  async function uploadBanner(eventId:string){
    if(!banner||!activeOrg)return form.banner_url||null;
    if(banner.size>8*1024*1024)throw new Error('Event banner must be 8 MB or smaller.');
    const ext=banner.name.split('.').pop()?.toLowerCase()||'jpg'; const path=`${activeOrg.id}/${eventId}/banner-${Date.now()}.${ext}`;
    const {error}=await supabase.storage.from('event-banners').upload(path,banner,{upsert:true,contentType:banner.type}); if(error)throw error;
    return supabase.storage.from('event-banners').getPublicUrl(path).data.publicUrl;
  }

  async function saveEvent(e:FormEvent){ e.preventDefault(); if(!activeOrg)return; setSaving(true);setError('');setMessage('');try{
    const public_slug=form.public_slug||`${slugify(form.title)}-${Math.random().toString(36).slice(2,8)}`;
    const base:any={organisation_id:activeOrg.id,title:form.title.trim(),description:form.description||null,venue:form.venue||null,address:form.address||null,start_at:new Date(form.start_at).toISOString(),end_at:form.end_at?new Date(form.end_at).toISOString():null,capacity:form.capacity?Number(form.capacity):null,status:form.status,public_slug,updated_at:new Date().toISOString()};
    let eventId=form.id;
    if(form.id){const {error}=await supabase.from('events').update(base).eq('id',form.id).eq('organisation_id',activeOrg.id);if(error)throw error;} else {const {data,error}=await supabase.from('events').insert({...base,created_by:profile?.id??null}).select('id').single();if(error)throw error;eventId=data.id;}
    const bannerUrl=await uploadBanner(eventId); if(bannerUrl&&bannerUrl!==form.banner_url){const {error}=await supabase.from('events').update({banner_url:bannerUrl}).eq('id',eventId);if(error)throw error;}
    const existing=(events.find(x=>x.id===eventId)?.event_ticket_types??[]) as any[]; const keptIds=new Set<string>();
    for(let i=0;i<form.tickets.length;i++){const t=form.tickets[i];const payload:any={organisation_id:activeOrg.id,event_id:eventId,name:t.name.trim()||`Ticket ${i+1}`,description:t.description||null,price:Number(t.price||0),member_price:t.member_price===''?null:Number(t.member_price),quantity_available:t.quantity_available===''?null:Number(t.quantity_available),max_per_order:Number(t.max_per_order||10),is_active:t.is_active,sort_order:i};
      if(t.id){keptIds.add(t.id);const {error}=await supabase.from('event_ticket_types').update(payload).eq('id',t.id).eq('event_id',eventId);if(error)throw error;} else {const {data,error}=await supabase.from('event_ticket_types').insert(payload).select('id').single();if(error)throw error;keptIds.add(data.id);}
    }
    for(const old of existing.filter(x=>!keptIds.has(x.id))){const issued=(events.find(x=>x.id===eventId)?.event_tickets??[]).some(t=>t.ticket_type_id===old.id); if(issued) await supabase.from('event_ticket_types').update({is_active:false}).eq('id',old.id); else await supabase.from('event_ticket_types').delete().eq('id',old.id);}
    await supabase.from('audit_logs').insert({organisation_id:activeOrg.id,user_id:profile?.id??null,action:form.id?'event.updated':'event.created',resource:'events',resource_id:eventId,new_value:{...base,banner_url:bannerUrl,ticket_types:form.tickets},user_agent:navigator.userAgent});
    setOpen(false);setForm(emptyForm());setBanner(null);setMessage(form.id?'Event saved.':'Event created.');load();
  }catch(err:any){setError(err?.message??'Unable to save event');}finally{setSaving(false);}}
  async function removeEvent(id:string){ if(!confirm('Delete this event and its ticket setup?'))return; const {error}=await supabase.from('events').delete().eq('id',id); if(error)alert(error.message); else load(); }
  function shareUrl(e:EventRow){return `${window.location.origin}/events/${e.public_slug}`;}
  async function copyLink(e:EventRow){const url=shareUrl(e);try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(url);else window.prompt('Copy this event link',url);setMessage('Public event link copied.');}catch{window.prompt('Copy this event link',url);}}

  return <div className="space-y-6">
    <PageHeader title="Events & Ticketing" description={`${events.length} events · ${totalTickets} issued tickets`} actions={<div className="flex flex-wrap gap-2"><Link className="btn-secondary" to="/admin/events/checkin"><QrCode className="h-4 w-4"/> Check-in Scanner</Link><button className="btn-primary" onClick={openNew}><Plus className="h-4 w-4"/> New Event</button></div>} />
    {message&&<div className="rounded-lg bg-green-50 p-3 text-sm text-green-700">{message}</div>}
    <div className="grid gap-4 md:grid-cols-3"><div className="card p-4"><p className="text-xs text-slate-500">Published</p><p className="mt-1 text-2xl font-bold">{events.filter(e=>e.status==='published').length}</p></div><div className="card p-4"><p className="text-xs text-slate-500">Tickets issued</p><p className="mt-1 text-2xl font-bold">{totalTickets}</p></div><div className="card p-4"><p className="text-xs text-slate-500">Checked in</p><p className="mt-1 text-2xl font-bold">{events.reduce((n,e)=>n+(e.event_tickets?.filter(t=>t.status==='used').length??0),0)}</p></div></div>
    {loading?<div className="card h-40 animate-pulse"/>:<div className="grid gap-4 lg:grid-cols-2">{events.map(e=><div key={e.id} className="card overflow-hidden">{e.banner_url&&<img src={e.banner_url} alt={`${e.title} banner`} className="h-44 w-full object-cover"/>}<div className="p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-primary-700"/><h3 className="font-semibold text-slate-900">{e.title}</h3></div><p className="mt-2 text-sm text-slate-500">{e.description}</p></div><StatusBadge status={e.status}/></div><div className="mt-4 space-y-2 text-sm text-slate-600"><p>{new Date(e.start_at).toLocaleString()}</p><p className="flex items-center gap-2"><MapPin className="h-4 w-4"/>{e.venue??'Venue TBC'}</p><p className="flex items-center gap-2"><Ticket className="h-4 w-4"/>{e.event_tickets?.length??0} issued · {e.capacity??'Unlimited'} capacity</p></div><div className="mt-4 border-t pt-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Ticket types</p><div className="mt-2 flex flex-wrap gap-2">{e.event_ticket_types?.map((t:any)=><span key={t.id} className="rounded-full bg-slate-100 px-3 py-1 text-xs">{t.name}: {Number(t.price)===0?'Free':formatCurrency(Number(t.price), currency)}</span>)}</div></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>openEdit(e)} className="btn-secondary"><Edit3 className="h-4 w-4"/> Edit</button>{e.public_slug&&<><a href={shareUrl(e)} target="_blank" rel="noreferrer" className="btn-secondary"><LinkIcon className="h-4 w-4"/> Public page</a><button type="button" onClick={()=>void copyLink(e)} className="btn-secondary"><Copy className="h-4 w-4"/> Copy link</button></>}<button type="button" onClick={()=>void removeEvent(e.id)} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm text-red-600"><Trash2 className="h-4 w-4"/>Delete</button></div></div></div>)}</div>}
    <Modal open={open} onClose={()=>setOpen(false)} title={form.id?'Edit Event':'Create Event'} description="Event details, banner and multiple ticket types." size="xl" footer={<><button type="button" onClick={()=>setOpen(false)} className="btn-secondary">Cancel</button><button form="event-form" disabled={saving} className="btn-primary">{saving?'Saving…':form.id?'Save Event':'Create Event'}</button></>}>
      <form id="event-form" onSubmit={saveEvent} className="space-y-5">{error&&<div className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</div>}
        <div className="grid gap-4 md:grid-cols-2"><FormField label="Event title" required><TextInput required value={form.title} onChange={e=>set('title',e.target.value)}/></FormField><FormField label="Status"><Select value={form.status} onChange={e=>set('status',e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="cancelled">Cancelled</option><option value="completed">Completed</option></Select></FormField><FormField label="Start" required><TextInput required type="datetime-local" value={form.start_at} onChange={e=>set('start_at',e.target.value)}/></FormField><FormField label="End"><TextInput type="datetime-local" value={form.end_at} onChange={e=>set('end_at',e.target.value)}/></FormField><FormField label="Venue"><TextInput value={form.venue} onChange={e=>set('venue',e.target.value)}/></FormField><FormField label="Capacity"><TextInput type="number" min="0" value={form.capacity} onChange={e=>set('capacity',e.target.value)}/></FormField><FormField label="Address" className="md:col-span-2"><TextInput value={form.address} onChange={e=>set('address',e.target.value)}/></FormField><FormField label="Description" className="md:col-span-2"><TextArea value={form.description} onChange={e=>set('description',e.target.value)}/></FormField></div>
        <section className="rounded-xl border p-4"><div className="flex items-center gap-2"><ImageIcon className="h-5 w-5"/><h3 className="font-semibold">Event / ticket banner</h3></div>{form.banner_url&&<img src={form.banner_url} alt="Current event banner" className="mt-3 h-36 w-full rounded-lg object-cover"/>}<label className="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-lg border px-4 py-2 text-sm font-medium"><ImageIcon className="h-4 w-4"/> {form.banner_url?'Replace banner':'Upload banner'}<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>setBanner(e.target.files?.[0]??null)}/></label>{banner&&<span className="ml-3 text-xs text-slate-500">{banner.name}</span>}</section>
        <section className="border-t pt-4"><div className="flex items-center justify-between"><div><h3 className="font-medium">Ticket types</h3><p className="text-xs text-slate-500">Add Family, Single, Child, VIP or any other ticket type.</p></div><button type="button" className="btn-secondary" onClick={()=>setForm((f:any)=>({...f,tickets:[...f.tickets,newTicket()]}))}><Plus className="h-4 w-4"/> Add ticket type</button></div><div className="mt-4 space-y-4">{form.tickets.map((t:TicketType,i:number)=><div key={t.id??i} className="rounded-xl border p-4"><div className="grid gap-4 md:grid-cols-3"><FormField label="Ticket name" required><TextInput required value={t.name} onChange={e=>setTicket(i,'name',e.target.value)}/></FormField><FormField label="Public price"><TextInput type="number" step="0.01" min="0" value={t.price} onChange={e=>setTicket(i,'price',e.target.value)}/></FormField><FormField label="Member price"><TextInput type="number" step="0.01" min="0" value={t.member_price} onChange={e=>setTicket(i,'member_price',e.target.value)}/></FormField><FormField label="Quantity available"><TextInput type="number" min="0" value={t.quantity_available} onChange={e=>setTicket(i,'quantity_available',e.target.value)}/></FormField><FormField label="Max per order"><TextInput type="number" min="1" value={t.max_per_order} onChange={e=>setTicket(i,'max_per_order',e.target.value)}/></FormField><FormField label="Description"><TextInput value={t.description} onChange={e=>setTicket(i,'description',e.target.value)}/></FormField></div><div className="mt-3 flex justify-between"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={t.is_active} onChange={e=>setTicket(i,'is_active',e.target.checked)}/> Active</label>{form.tickets.length>1&&<button type="button" className="text-sm text-red-600" onClick={()=>setForm((f:any)=>({...f,tickets:f.tickets.filter((_:any,idx:number)=>idx!==i)}))}>Remove ticket type</button>}</div></div>)}</div></section>
      </form>
    </Modal>
  </div>;
}
