import { useEffect, useRef, useState } from 'react';
import { Camera, CheckCircle2, QrCode, Search, XCircle } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import { PageHeader } from '@/components/ui/PageHeader';

type Result = { type:'success'|'used'|'invalid'; title:string; detail:string } | null;

export function EventCheckin(){
 const { activeOrg, profile }=useAuth(); const [token,setToken]=useState(''); const [result,setResult]=useState<Result>(null); const [scanning,setScanning]=useState(false); const videoRef=useRef<HTMLVideoElement>(null); const streamRef=useRef<MediaStream|null>(null); const timerRef=useRef<number|null>(null);
 async function verify(raw:string){const clean=raw.trim().split('/').pop()||raw.trim(); if(!clean||!activeOrg)return; const {data,error}=await supabase.from('event_tickets').select('id,status,attendee_name,checked_in_at,events(title),event_ticket_types(name)').eq('organisation_id',activeOrg.id).eq('qr_token',clean).maybeSingle(); if(error||!data){setResult({type:'invalid',title:'Invalid ticket',detail:'No ticket was found for this club.'});return;} const d:any=data; if(d.status==='used'||d.checked_in_at){setResult({type:'used',title:'Already checked in',detail:`${d.attendee_name} · ${d.events?.title??'Event'} · first scan ${new Date(d.checked_in_at).toLocaleString('en-NZ')}`});return;} if(d.status!=='valid'){setResult({type:'invalid',title:'Ticket not valid',detail:`This ticket is ${d.status}.`});return;} const now=new Date().toISOString(); const {error:updateError}=await supabase.from('event_tickets').update({status:'used',checked_in_at:now,checked_in_by:profile?.id??null,checkin_method:'qr'}).eq('id',d.id).eq('status','valid'); if(updateError){setResult({type:'invalid',title:'Could not check in',detail:updateError.message});return;} setResult({type:'success',title:'Check-in successful',detail:`${d.attendee_name} · ${d.event_ticket_types?.name??'Ticket'} · ${d.events?.title??'Event'}`}); setToken('');}
 function stop(){if(timerRef.current)window.clearInterval(timerRef.current);streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setScanning(false);}
 async function start(){setResult(null); try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});streamRef.current=stream;setScanning(true);if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play();} const Detector=(window as any).BarcodeDetector; if(!Detector){setResult({type:'invalid',title:'Camera opened',detail:'Automatic QR detection is not supported in this browser. Use Chrome/Edge or enter the ticket code manually below.'});return;} const detector=new Detector({formats:['qr_code']}); timerRef.current=window.setInterval(async()=>{if(!videoRef.current||videoRef.current.readyState<2)return; try{const codes=await detector.detect(videoRef.current); if(codes?.[0]?.rawValue){stop();await verify(codes[0].rawValue);}}catch{}},500);}catch(e:any){setResult({type:'invalid',title:'Camera unavailable',detail:e?.message??'Please allow camera access or use manual check-in.'});}}
 useEffect(()=>()=>stop(),[]);
 return <div className="space-y-6"><PageHeader title="Event Check-in" description="Scan a ClubOS QR ticket or enter its code manually."/><div className="grid gap-6 lg:grid-cols-2"><div className="card p-5"><div className="flex items-center gap-2"><QrCode className="h-5 w-5 text-primary-700"/><h2 className="font-semibold">QR scanner</h2></div><div className="mt-4 overflow-hidden rounded-xl bg-slate-950 aspect-video flex items-center justify-center">{scanning?<video ref={videoRef} className="h-full w-full object-cover" playsInline muted/>:<Camera className="h-12 w-12 text-slate-500"/>}</div><div className="mt-4 flex gap-2">{scanning?<button className="btn-secondary" onClick={stop}>Stop camera</button>:<button className="btn-primary" onClick={start}><Camera className="h-4 w-4"/> Start camera</button>}</div><div className="mt-6 border-t pt-5"><label className="text-sm font-medium">Manual ticket code</label><div className="mt-2 flex gap-2"><input className="input flex-1" value={token} onChange={e=>setToken(e.target.value)} placeholder="e.g. CLUBOS-DEMO-VALID-001"/><button className="btn-secondary" onClick={()=>verify(token)}><Search className="h-4 w-4"/> Verify</button></div><p className="mt-2 text-xs text-slate-500">Demo valid code: CLUBOS-DEMO-VALID-001 · used code: CLUBOS-DEMO-USED-002</p></div></div><div className="card p-6">{!result?<div className="flex h-full min-h-64 flex-col items-center justify-center text-center text-slate-500"><QrCode className="h-12 w-12"/><p className="mt-3 font-medium">Ready to scan</p><p className="mt-1 text-sm">The result will appear here.</p></div>:<div className={`rounded-xl p-5 ${result.type==='success'?'bg-emerald-50 text-emerald-800':result.type==='used'?'bg-amber-50 text-amber-800':'bg-red-50 text-red-800'}`}>{result.type==='success'?<CheckCircle2 className="h-10 w-10"/>:<XCircle className="h-10 w-10"/>}<h2 className="mt-3 text-xl font-bold">{result.title}</h2><p className="mt-2 text-sm">{result.detail}</p></div>}</div></div></div>;
}
