import { ChangeEvent, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import * as XLSX from 'xlsx';
import { ArrowLeft, FileSpreadsheet, Upload, CheckCircle2, AlertTriangle, Download } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { supabase } from '@/lib/supabase';

type Row = Record<string, string>;
type TypeRow = { id:string; name:string; voting_rights:boolean };
type Preview = { row:number; data:Row; errors:string[]; duplicate:boolean };

const aliases:Record<string,string[]> = {
  first_name:['first name','firstname','first_name','given name'], last_name:['last name','lastname','last_name','surname','family name'],
  email:['email','email address'], mobile:['mobile','phone','mobile phone','phone number'], date_of_birth:['date of birth','dob','birth date'],
  address_line1:['address','address line 1','street address'], suburb:['suburb'], city:['city','town'], region:['region','state'], postcode:['postcode','postal code','zip'],
  country:['country'], status:['status'], membership_type:['membership type','membership','member type'], member_number:['member number','member #','membership number'],
  emergency_name:['emergency contact','emergency contact name'], emergency_relationship:['emergency relationship','emergency contact relationship'], emergency_mobile:['emergency phone','emergency mobile'],
};
function norm(v:string){return v.trim().toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ')}
function mapRow(raw:Record<string,unknown>):Row { const headers=Object.keys(raw); const out:Row={}; for(const [key,names] of Object.entries(aliases)){const found=headers.find(h=>names.includes(norm(h))); if(found) out[key]=String(raw[found]??'').trim();} return out; }

export function MemberImport(){
 const {activeOrg}=useAuth(); const navigate=useNavigate(); const [types,setTypes]=useState<TypeRow[]>([]); const [preview,setPreview]=useState<Preview[]>([]); const [fileName,setFileName]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{if(activeOrg)supabase.from('membership_types').select('id,name,voting_rights').eq('organisation_id',activeOrg.id).eq('is_active',true).then(({data})=>setTypes((data??[]) as TypeRow[]));},[activeOrg]);
 async function choose(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!activeOrg)return;setFileName(file.name);setMessage('');let raw:Record<string,unknown>[]=[]; if(file.name.toLowerCase().endsWith('.csv')){const text=await file.text();const wb=XLSX.read(text,{type:'string'});raw=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});}else{const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array'});raw=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});}
  const {data:existing}=await supabase.from('members').select('email,member_number').eq('organisation_id',activeOrg.id); const emails=new Set((existing??[]).map((r:any)=>String(r.email||'').toLowerCase()).filter(Boolean)); const nums=new Set((existing??[]).map((r:any)=>String(r.member_number||'').toLowerCase()).filter(Boolean));
  setPreview(raw.map((r,i)=>{const d=mapRow(r),errors:string[]=[];if(!d.first_name)errors.push('First name required');if(!d.last_name)errors.push('Last name required');if(d.email&&!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(d.email))errors.push('Invalid email');if(d.membership_type&&!types.some(t=>norm(t.name)===norm(d.membership_type)))errors.push('Unknown membership type');const duplicate=Boolean((d.email&&emails.has(d.email.toLowerCase()))||(d.member_number&&nums.has(d.member_number.toLowerCase())));return{row:i+2,data:d,errors,duplicate};})); }
 const valid=useMemo(()=>preview.filter(r=>r.errors.length===0&&!r.duplicate),[preview]);
 async function runImport(){if(!activeOrg||valid.length===0)return;setBusy(true);setMessage('');try{const {count}=await supabase.from('members').select('id',{count:'exact',head:true}).eq('organisation_id',activeOrg.id);let seq=(count??0)+1;let imported=0;for(const item of valid){const d=item.data;const type=types.find(t=>norm(t.name)===norm(d.membership_type||''));const memberNumber=d.member_number||`DSC-${String(seq++).padStart(6,'0')}`;const {data:m,error}=await supabase.from('members').insert({organisation_id:activeOrg.id,member_number:memberNumber,first_name:d.first_name,last_name:d.last_name,email:d.email||null,mobile:d.mobile||null,date_of_birth:d.date_of_birth||null,address_line1:d.address_line1||null,suburb:d.suburb||null,city:d.city||null,region:d.region||null,postcode:d.postcode||null,country:d.country||'New Zealand',status:d.status||'active',joined_date:new Date().toISOString().slice(0,10),member_since:new Date().toISOString().slice(0,10),voting_eligible:type?.voting_rights??false}).select('id').single();if(error)throw new Error(`Row ${item.row}: ${error.message}`);if(type)await supabase.from('memberships').insert({organisation_id:activeOrg.id,member_id:m.id,membership_type_id:type.id,status:'active',start_date:new Date().toISOString().slice(0,10)});if(d.emergency_name)await supabase.from('member_emergency_contacts').insert({organisation_id:activeOrg.id,member_id:m.id,full_name:d.emergency_name,relationship:d.emergency_relationship||null,mobile:d.emergency_mobile||null});imported++;}setMessage(`${imported} members imported successfully.`);setPreview([]);}catch(e:any){setMessage(e?.message||'Import failed.')}finally{setBusy(false)}}
 function template(){const csv='First Name,Last Name,Email,Mobile,Date of Birth,Address,Suburb,City,Region,Postcode,Country,Status,Membership Type,Member Number,Emergency Contact Name,Emergency Relationship,Emergency Mobile\nAroha,Example,aroha@example.com,+64 21 555 0101,1990-01-15,1 Example Street,Johnsonville,Wellington,Wellington,6037,New Zealand,active,Adult,,Sam Example,Partner,+64 21 555 0102';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='clubos-member-import-template.csv';a.click();URL.revokeObjectURL(a.href)}
 return <div className="space-y-6"><div><Link to="/admin/members" className="inline-flex items-center gap-1 text-sm text-slate-500"><ArrowLeft className="h-4 w-4"/>Member Register</Link><h1 className="mt-2 text-2xl font-bold">Import Members</h1><p className="text-sm text-slate-500">Upload CSV or Excel (.xlsx/.xls), review validation results, then import only valid non-duplicate rows.</p></div>
 <div className="card p-5"><div className="flex flex-wrap gap-3"><label className="btn-primary cursor-pointer"><Upload className="h-4 w-4"/>Select CSV / Excel<input className="hidden" type="file" accept=".csv,.xlsx,.xls" onChange={choose}/></label><button className="btn-secondary" onClick={template}><Download className="h-4 w-4"/>Download CSV template</button></div>{fileName&&<p className="mt-3 text-sm text-slate-600"><FileSpreadsheet className="mr-1 inline h-4 w-4"/>{fileName}</p>}</div>
 {preview.length>0&&<div className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><p className="font-medium">Import preview</p><p className="text-sm text-slate-500">{valid.length} ready · {preview.filter(x=>x.duplicate).length} duplicates · {preview.filter(x=>x.errors.length).length} rows with errors</p></div><button disabled={busy||valid.length===0} onClick={runImport} className="btn-primary"><CheckCircle2 className="h-4 w-4"/>{busy?'Importing…':`Import ${valid.length} valid members`}</button></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr><th className="px-3 py-2 text-left">Row</th><th className="px-3 py-2 text-left">Name</th><th className="px-3 py-2 text-left">Email</th><th className="px-3 py-2 text-left">Membership</th><th className="px-3 py-2 text-left">Result</th></tr></thead><tbody className="divide-y">{preview.map(r=><tr key={r.row}><td className="px-3 py-2">{r.row}</td><td className="px-3 py-2">{r.data.first_name} {r.data.last_name}</td><td className="px-3 py-2">{r.data.email||'—'}</td><td className="px-3 py-2">{r.data.membership_type||'—'}</td><td className="px-3 py-2">{r.duplicate?<span className="inline-flex items-center gap-1 text-amber-700"><AlertTriangle className="h-4 w-4"/>Duplicate — skipped</span>:r.errors.length?<span className="text-red-600">{r.errors.join('; ')}</span>:<span className="text-emerald-700">Ready</span>}</td></tr>)}</tbody></table></div></div>}
 {message&&<div className="rounded-lg border border-slate-200 bg-white p-4 text-sm">{message}</div>}<div className="flex justify-end"><button className="btn-secondary" onClick={()=>navigate('/admin/members')}>Back to Member Register</button></div></div>
}