import { useEffect, useState } from 'react';
import { Image as ImageIcon, Plus, Pencil, Trash2 } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import { PageHeader } from '@/components/ui/PageHeader';
import { Modal } from '@/components/ui/Modal';
import { FormField, Select, TextArea, TextInput } from '@/components/ui/FormField';
import { formatCurrency } from '@/lib/utils';
import { useOrganisationCurrency } from '@/lib/useOrganisationCurrency';
import { notifySuccess } from '@/lib/notifications';

type Product={id:string;name:string;description:string|null;sku:string|null;sizes:string[]|null;price:number;stock_quantity:number;status:string;image_url_1:string|null;image_url_2:string|null};
const empty={name:'',description:'',sizes:'',price:'0',stock_quantity:'0',status:'active',image_url_1:'',image_url_2:''};
export function MerchandisePage(){
 const {activeOrg}=useAuth();const {currency}=useOrganisationCurrency();const [rows,setRows]=useState<Product[]>([]);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Product|null>(null);const [form,setForm]=useState<any>(empty);const [files,setFiles]=useState<(File|null)[]>([null,null]);const [error,setError]=useState('');const [saving,setSaving]=useState(false);
 async function load(){if(!activeOrg)return;const {data,error}=await supabase.from('merchandise_products').select('*').eq('organisation_id',activeOrg.id).order('name');if(error)setError(error.message);setRows((data??[]) as Product[])} useEffect(()=>{load()},[activeOrg?.id]);
 function add(){setEditing(null);setForm(empty);setFiles([null,null]);setError('');setOpen(true)} function edit(p:Product){setEditing(p);setForm({...p,sizes:(p.sizes??[]).join(', '),price:String(p.price),stock_quantity:String(p.stock_quantity)});setFiles([null,null]);setError('');setOpen(true)}
 async function upload(productId:string,file:File|null,index:number,current:string){if(!file||!activeOrg)return current||null;if(file.size>6*1024*1024)throw new Error('Each merchandise image must be 6 MB or smaller.');const ext=file.name.split('.').pop()||'jpg';const path=`${activeOrg.id}/${productId}/image-${index+1}-${Date.now()}.${ext}`;const {error}=await supabase.storage.from('merchandise-images').upload(path,file,{upsert:true,contentType:file.type});if(error)throw error;return supabase.storage.from('merchandise-images').getPublicUrl(path).data.publicUrl}
 async function save(){if(!activeOrg||!form.name.trim())return;setSaving(true);setError('');try{let id=editing?.id;const base={organisation_id:activeOrg.id,name:form.name.trim(),description:form.description?.trim()||null,sizes:String(form.sizes||'').split(',').map((s:string)=>s.trim()).filter(Boolean),sku:null,price:Number(form.price||0),stock_quantity:Number(form.stock_quantity||0),status:form.status};if(id){const {error}=await supabase.from('merchandise_products').update(base).eq('id',id);if(error)throw error}else{const {data,error}=await supabase.from('merchandise_products').insert(base).select('id').single();if(error)throw error;id=data.id}const u1=await upload(id!,files[0],0,form.image_url_1||'');const u2=await upload(id!,files[1],1,form.image_url_2||'');const {error}=await supabase.from('merchandise_products').update({image_url_1:u1,image_url_2:u2}).eq('id',id);if(error)throw error;setOpen(false);notifySuccess(editing?'Merchandise updated.':'Merchandise created.');load()}catch(e:any){setError(e.message||'Unable to save product')}finally{setSaving(false)}}
 async function remove(p:Product){if(!confirm(`Delete “${p.name}”?`))return;const {error}=await supabase.from('merchandise_products').delete().eq('id',p.id);if(error)alert(error.message);else load()}
 return <div className="space-y-6"><PageHeader title="Merchandise" description="Create products with up to two images for members to preview." actions={<button className="btn-primary" onClick={add}><Plus className="h-4 w-4"/> New Product</button>}/>{error&&!open&&<div className="rounded bg-red-50 p-3 text-red-700">{error}</div>}<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{rows.map(p=><div key={p.id} className="card overflow-hidden"><div className="grid h-44 grid-cols-2 bg-slate-100">{[p.image_url_1,p.image_url_2].map((u,i)=>u?<img key={i} src={u} className="h-44 w-full object-cover" alt={`${p.name} ${i+1}`}/>:<div key={i} className="flex items-center justify-center text-slate-300"><ImageIcon/></div>)}</div><div className="p-5"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{p.name}</h3><p className="text-sm text-slate-500">{p.sizes?.length ? `Sizes: ${p.sizes.join(', ')}` : 'One size'}</p></div><span className="font-bold text-primary-700">{formatCurrency(Number(p.price),currency)}</span></div><p className="mt-2 text-sm text-slate-600">{p.description}</p><p className="mt-3 text-xs text-slate-500">Stock: {p.stock_quantity} · {p.status}</p><div className="mt-4 flex gap-2"><button className="btn-secondary flex-1" onClick={()=>edit(p)}><Pencil className="h-4 w-4"/> Edit</button><button className="btn-ghost text-red-600" onClick={()=>remove(p)}><Trash2 className="h-4 w-4"/></button></div></div></div>)}</div>
 <Modal open={open} onClose={()=>setOpen(false)} title={editing?'Edit Merchandise':'New Merchandise'} size="lg" footer={<><button className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary" disabled={saving} onClick={save}>{saving?'Saving…':'Save Product'}</button></>}><div className="grid gap-4 md:grid-cols-2">{error&&<div className="md:col-span-2 rounded bg-red-50 p-3 text-sm text-red-700">{error}</div>}<FormField label="Product name" required className="md:col-span-2"><TextInput value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></FormField><FormField label="Description" className="md:col-span-2"><TextArea value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></FormField><FormField label="Sizes" helpText="Enter sizes separated by commas, e.g. S, M, L, XL"><TextInput placeholder="S, M, L, XL" value={form.sizes||''} onChange={e=>setForm({...form,sizes:e.target.value})}/></FormField><FormField label="Price"><TextInput type="number" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></FormField><FormField label="Stock"><TextInput type="number" value={form.stock_quantity} onChange={e=>setForm({...form,stock_quantity:e.target.value})}/></FormField><FormField label="Status"><Select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option><option value="sold_out">Sold out</option></Select></FormField>{[0,1].map(i=><FormField key={i} label={`Product image ${i+1}`} helpText="JPG, PNG or WebP; max 6 MB"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFiles(f=>f.map((x,j)=>j===i?(e.target.files?.[0]||null):x))} className="input"/>{(i===0?form.image_url_1:form.image_url_2)&&<img src={i===0?form.image_url_1:form.image_url_2} className="mt-2 h-24 w-full rounded object-cover"/>}</FormField>)}</div></Modal></div>
}
