import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Plus, Users, ShieldCheck, Vote, Lock, Play, Square, Pencil, Clock3 } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import { PageHeader } from '@/components/ui/PageHeader';
import { Modal } from '@/components/ui/Modal';
import { FormField, Select, TextArea, TextInput } from '@/components/ui/FormField';
import { StatusBadge } from '@/components/ui/StatusBadge';

interface Motion {id:string;title:string;description:string|null;voting_audience:string;voting_method:string;majority_percent:number;quorum_percent:number;opens_at:string;closes_at:string|null;status:string;total_votes:number;yes_votes:number;no_votes:number;abstain_votes:number}
const blank={title:'',description:'',voting_audience:'all_eligible_members',voting_method:'named',majority_percent:'50',quorum_percent:'0',opens_at:'',closes_at:'',status:'draft'};
export function MotionsPage(){
 const {activeOrg,profile}=useAuth(); const [motions,setMotions]=useState<Motion[]>([]);const[open,setOpen]=useState(false);const[editingId,setEditingId]=useState<string|null>(null);const[form,setForm]=useState(blank);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
 async function load(){if(!activeOrg)return;const{data,error}=await supabase.rpc('get_admin_motions',{p_org_id:activeOrg.id});if(error){console.error(error);return;}setMotions((data??[]) as Motion[])} useEffect(()=>{load()},[activeOrg?.id]);
 const pending=useMemo(()=>motions.filter(m=>m.status==='open').length,[motions]);const set=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
 async function create(e:FormEvent){e.preventDefault();if(!activeOrg)return;setSaving(true);setError('');const now=new Date();const opens=form.opens_at?new Date(form.opens_at):now;const closes=form.closes_at?new Date(form.closes_at):null;if(!closes||Number.isNaN(closes.getTime())){setError('A motion closing date and time is required.');setSaving(false);return;}if(closes<=opens){setError('The motion closing date/time must be after the opening date/time.');setSaving(false);return;}const payload={organisation_id:activeOrg.id,title:form.title,description:form.description||null,proposed_by:profile?.id??null,voting_audience:form.voting_audience,voting_method:form.voting_method,majority_percent:Number(form.majority_percent||50),quorum_percent:Number(form.quorum_percent||0),opens_at:opens.toISOString(),closes_at:closes.toISOString(),status:form.status};const result=editingId?await supabase.from('governance_motions').update({...payload,updated_at:new Date().toISOString()}).eq('id',editingId).eq('organisation_id',activeOrg.id):await supabase.from('governance_motions').insert(payload);if(result.error)setError(result.error.message);else{setOpen(false);setEditingId(null);setForm(blank);await load()}setSaving(false)}
 function localDateTime(d:Date){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
 function openNew(){const now=new Date();const close=new Date(now.getTime()+7*24*60*60*1000);setEditingId(null);setForm({...blank,opens_at:localDateTime(now),closes_at:localDateTime(close)});setError('');setOpen(true)}
 function edit(m:Motion){const local=(iso:string|null)=>iso?localDateTime(new Date(iso)):'';setEditingId(m.id);setForm({title:m.title,description:m.description??'',voting_audience:m.voting_audience,voting_method:m.voting_method,majority_percent:String(m.majority_percent),quorum_percent:String(m.quorum_percent),opens_at:local(m.opens_at),closes_at:local(m.closes_at),status:m.status});setError('');setOpen(true)}
 async function status(id:string,status:string){const{error}=await supabase.from('governance_motions').update({status,opens_at:status==='open'?new Date().toISOString():undefined,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else load()}
 return <div className="space-y-6"><PageHeader title="Motions & Voting" description={`${motions.length} motions · ${pending} currently open`} actions={<button className="btn-primary" onClick={openNew}><Plus className="h-4 w-4"/> New Motion</button>}/>
 <div className="space-y-4">{motions.map(m=>{const yes=Number(m.yes_votes??0),no=Number(m.no_votes??0),abs=Number(m.abstain_votes??0),total=Number(m.total_votes??0);return <div className="card p-5" key={m.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Vote className="h-5 w-5 text-primary-700"/><h3 className="font-semibold">{m.title}</h3></div><p className="mt-2 max-w-2xl text-sm text-slate-600">{m.description}</p></div><StatusBadge status={m.status}/></div><div className="mt-4 flex flex-wrap gap-3 text-xs text-slate-500"><span className="flex gap-1 items-center">{m.voting_audience==='committee_only'?<ShieldCheck className="h-4 w-4"/>:<Users className="h-4 w-4"/>}{m.voting_audience==='committee_only'?'Committee only':'All eligible members'}</span><span className="flex gap-1 items-center"><Lock className="h-4 w-4"/>{m.voting_method==='secret'?'Secret':'Named'} ballot</span><span>Majority: {m.majority_percent}%</span><span>Quorum: {m.quorum_percent}%</span><span className="flex items-center gap-1"><Clock3 className="h-4 w-4"/>{m.closes_at?`Closes ${new Date(m.closes_at).toLocaleString()}`:'No closing date'}</span></div><div className="mt-4 grid max-w-md grid-cols-4 gap-2 text-center text-xs"><div className="rounded bg-slate-50 p-2"><b className="block text-base">{total}</b>Total</div><div className="rounded bg-green-50 p-2"><b className="block text-base">{yes}</b>Yes</div><div className="rounded bg-red-50 p-2"><b className="block text-base">{no}</b>No</div><div className="rounded bg-slate-50 p-2"><b className="block text-base">{abs}</b>Abstain</div></div><div className="mt-4 flex gap-2"><button className="btn-secondary" onClick={()=>edit(m)}><Pencil className="h-4 w-4"/>Edit</button>{m.status==='draft'&&<button className="btn-primary" onClick={()=>status(m.id,'open')}><Play className="h-4 w-4"/>Open voting</button>}{m.status==='open'&&<button className="btn-secondary" onClick={()=>status(m.id,'closed')}><Square className="h-4 w-4"/>Close voting</button>}</div></div>})}</div>
 <Modal open={open} onClose={()=>{setOpen(false);setEditingId(null);setForm(blank);setError('')}} title={editingId?'Edit Motion':'Create Motion'} description="Choose exactly who is entitled to vote." size="lg" footer={<><button className="btn-secondary" onClick={()=>{setOpen(false);setEditingId(null);setForm(blank);setError('')}}>Cancel</button><button form="motion-form" className="btn-primary" disabled={saving}>{saving?'Saving…':editingId?'Save Changes':'Create Motion'}</button></>}><form id="motion-form" onSubmit={create} className="space-y-4">{error&&<div className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</div>}<FormField label="Motion title" required><TextInput required value={form.title} onChange={e=>set('title',e.target.value)}/></FormField><FormField label="Motion / resolution"><TextArea value={form.description} onChange={e=>set('description',e.target.value)}/></FormField><div className="grid gap-4 md:grid-cols-2"><FormField label="Voting audience"><Select value={form.voting_audience} onChange={e=>set('voting_audience',e.target.value)}><option value="all_eligible_members">All eligible members</option><option value="committee_only">Committee members only</option></Select></FormField><FormField label="Ballot"><Select value={form.voting_method} onChange={e=>set('voting_method',e.target.value)}><option value="named">Named vote</option><option value="secret">Secret ballot</option></Select></FormField><FormField label="Majority required (%)"><TextInput type="number" min="0" max="100" step="0.01" value={form.majority_percent} onChange={e=>set('majority_percent',e.target.value)}/></FormField><FormField label="Quorum / participation (%)"><TextInput type="number" min="0" max="100" step="0.01" value={form.quorum_percent} onChange={e=>set('quorum_percent',e.target.value)}/></FormField><FormField label="Voting opens"><TextInput type="datetime-local" value={form.opens_at} onChange={e=>set('opens_at',e.target.value)}/></FormField><FormField label="Motion closing date & time" required><TextInput required type="datetime-local" value={form.closes_at} onChange={e=>set('closes_at',e.target.value)}/></FormField><FormField label="Initial status"><Select value={form.status} onChange={e=>set('status',e.target.value)}><option value="draft">Draft</option><option value="open">Open for voting</option><option value="closed">Closed</option><option value="cancelled">Cancelled</option></Select></FormField></div></form></Modal>
 </div>
}
