import { useEffect, useMemo, useState } from 'react';
import { Calculator, Save, CreditCard } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';
import { useOrganisationCurrency } from '@/lib/useOrganisationCurrency';
import { formatCurrency } from '@/lib/utils';

type OrgFee = {
  fee_payer:'member'|'organisation'|'split'; member_share_percent:number;
  apply_provider_fees:boolean; apply_platform_fees:boolean; display_fee_breakdown:boolean;
};
type PlatformFee = { enabled:boolean; fixed_amount:number; percentage:number; minimum_fee:number|null; maximum_fee:number|null; currency:string };

export function PaymentFeeSettings(){
 const {activeOrg}=useAuth();
 const {currency}=useOrganisationCurrency();
 const [cfg,setCfg]=useState<OrgFee>({fee_payer:'organisation',member_share_percent:0,apply_provider_fees:true,apply_platform_fees:true,display_fee_breakdown:true});
 const [platform,setPlatform]=useState<PlatformFee>({enabled:false,fixed_amount:0,percentage:0,minimum_fee:null,maximum_fee:null,currency:'NZD'});
 const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
 const [base,setBase]=useState(100); const [providerFee,setProviderFee]=useState(2.2);
 useEffect(()=>{if(!activeOrg?.id)return;(async()=>{const[{data:o},{data:p}]=await Promise.all([
  supabase.from('organisation_fee_settings').select('*').eq('organisation_id',activeOrg.id).maybeSingle(),
  supabase.from('platform_transaction_fee_settings').select('*').eq('enabled',true).eq('active',true).order('effective_from',{ascending:false}).limit(1).maybeSingle()
 ]); if(o)setCfg(o as OrgFee); if(p)setPlatform(p as PlatformFee)})()},[activeOrg?.id]);
 const calc=useMemo(()=>{let pf=platform.enabled?(Number(platform.fixed_amount||0)+base*Number(platform.percentage||0)/100):0;if(platform.minimum_fee!=null)pf=Math.max(pf,Number(platform.minimum_fee));if(platform.maximum_fee!=null)pf=Math.min(pf,Number(platform.maximum_fee));pf=Math.round(pf*100)/100; const applicable=(cfg.apply_provider_fees?providerFee:0)+(cfg.apply_platform_fees?pf:0); const share=cfg.fee_payer==='member'?100:cfg.fee_payer==='organisation'?0:Number(cfg.member_share_percent||0); const memberFee=Math.round(applicable*share)/100; const orgFee=Math.round((applicable-memberFee)*100)/100; return {pf,memberFee,orgFee,total:Math.round((base+memberFee)*100)/100,net:Math.round((base-orgFee)*100)/100}},[base,providerFee,cfg,platform]);
 const save=async()=>{if(!activeOrg?.id)return;setSaving(true);setMessage('');const{error}=await supabase.from('organisation_fee_settings').upsert({organisation_id:activeOrg.id,...cfg,updated_at:new Date().toISOString()},{onConflict:'organisation_id'});setSaving(false);setMessage(error?error.message:'Fee policy saved.');};
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-slate-900">Payment & Fee Settings</h1><p className="mt-1 text-sm text-slate-500">Choose who pays transaction costs for {activeOrg?.trading_name}. ClubOS platform fees are configured by Platform Admin.</p></div>
 <div className="grid gap-6 xl:grid-cols-2"><div className="card p-6 space-y-5"><h2 className="font-semibold text-slate-900">Organisation fee policy</h2><div><label className="label">Who pays transaction fees?</label><select className="input" value={cfg.fee_payer} onChange={e=>{const v=e.target.value as OrgFee['fee_payer'];setCfg(c=>({...c,fee_payer:v,member_share_percent:v==='member'?100:v==='organisation'?0:c.member_share_percent}))}}><option value="member">Member pays 100%</option><option value="organisation">Organisation pays 100%</option><option value="split">Split by percentage</option></select></div>{cfg.fee_payer==='split'&&<div><label className="label">Member share of fees (%)</label><input type="number" min="0" max="100" step="1" className="input" value={cfg.member_share_percent} onChange={e=>setCfg(c=>({...c,member_share_percent:Math.max(0,Math.min(100,Number(e.target.value)))}))}/><p className="mt-1 text-xs text-slate-500">Organisation pays the remaining {100-Number(cfg.member_share_percent||0)}%.</p></div>}
 <label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={cfg.apply_provider_fees} onChange={e=>setCfg(c=>({...c,apply_provider_fees:e.target.checked}))}/>Apply payment-provider fees</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={cfg.apply_platform_fees} onChange={e=>setCfg(c=>({...c,apply_platform_fees:e.target.checked}))}/>Apply ClubOS platform transaction fees</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={cfg.display_fee_breakdown} onChange={e=>setCfg(c=>({...c,display_fee_breakdown:e.target.checked}))}/>Show fee breakdown to member at checkout</label><button onClick={save} disabled={saving} className="btn-primary inline-flex items-center gap-2"><Save className="h-4 w-4"/>{saving?'Saving…':'Save policy'}</button>{message&&<p className="text-sm text-slate-600">{message}</p>}</div>
 <div className="space-y-6"><div className="card p-6"><div className="flex items-center gap-2"><CreditCard className="h-5 w-5 text-primary-600"/><h2 className="font-semibold">Current ClubOS platform fee</h2></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><span className="text-slate-500">Status</span><p className="font-medium">{platform.enabled?'Enabled':'Disabled'}</p></div><div><span className="text-slate-500">Fee</span><p className="font-medium">{platform.currency} {Number(platform.fixed_amount||0).toFixed(2)} + {Number(platform.percentage||0)}%</p></div></div></div>
 <div className="card p-6"><div className="flex items-center gap-2"><Calculator className="h-5 w-5 text-primary-600"/><h2 className="font-semibold">Fee calculator</h2></div><div className="mt-4 grid grid-cols-2 gap-3"><label><span className="label">Base amount</span><input className="input" type="number" value={base} onChange={e=>setBase(Number(e.target.value)||0)}/></label><label><span className="label">Provider fee</span><input className="input" type="number" value={providerFee} onChange={e=>setProviderFee(Number(e.target.value)||0)}/></label></div><div className="mt-5 divide-y rounded-lg border text-sm"><div className="flex justify-between p-3"><span>ClubOS fee</span><strong>{formatCurrency(calc.pf,currency)}</strong></div><div className="flex justify-between p-3"><span>Member-paid fees</span><strong>{formatCurrency(calc.memberFee,currency)}</strong></div><div className="flex justify-between p-3"><span>Organisation-absorbed fees</span><strong>{formatCurrency(calc.orgFee,currency)}</strong></div><div className="flex justify-between p-3"><span>Member checkout total</span><strong>{formatCurrency(calc.total,currency)}</strong></div><div className="flex justify-between p-3"><span>Organisation net after absorbed fees</span><strong>{formatCurrency(calc.net,currency)}</strong></div></div></div></div></div></div>
}
