import { useEffect, useMemo, useState } from 'react';
import { Plus, Pencil, Archive, Users, Shield, Save } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import { Modal } from '@/components/ui/Modal';

type Role={id:string;name:string;description:string|null;is_system_role:boolean;sort_order:number;structure_group?:string|null;reports_to_role_id?:string|null;is_archived?:boolean};
type Permission={id:string;key:string;module_key:string;description:string|null};
type OrgUser={id:string;user_id:string;role_id:string|null;status:string;profiles?:{first_name:string|null;last_name:string|null;email:string}|null};
export function RolesStructure(){const {activeOrg}=useAuth();const [roles,setRoles]=useState<Role[]>([]);const [perms,setPerms]=useState<Permission[]>([]);const [users,setUsers]=useState<OrgUser[]>([]);const [selected,setSelected]=useState<Role|null>(null);const [name,setName]=useState('');const [description,setDescription]=useState('');const [selectedPerms,setSelectedPerms]=useState<Set<string>>(new Set());const [open,setOpen]=useState(false);const [error,setError]=useState('');const [group,setGroup]=useState('Administration');const [reportsTo,setReportsTo]=useState('');
 async function load(){if(!activeOrg)return;const [{data:r},{data:p},{data:u}]=await Promise.all([supabase.from('roles').select('*').eq('organisation_id',activeOrg.id).order('sort_order'),supabase.from('permissions').select('*').order('module_key').order('key'),supabase.from('organisation_users').select('id,user_id,role_id,status,profiles:user_id(first_name,last_name,email)').eq('organisation_id',activeOrg.id).order('created_at')]);setRoles((r??[]) as Role[]);setPerms((p??[]) as Permission[]);setUsers((u??[]) as any)}
 useEffect(()=>{load()},[activeOrg]);
 const counts=useMemo(()=>Object.fromEntries(roles.map(r=>[r.id,users.filter(u=>u.role_id===r.id&&u.status==='active').length])),[roles,users]);
 async function edit(role?:Role){setError('');setSelected(role??null);setName(role?.name??'');setDescription(role?.description??'');setGroup(role?.structure_group??'Administration');setReportsTo(role?.reports_to_role_id??'');if(role){const {data}=await supabase.from('role_permissions').select('permission_id').eq('role_id',role.id);setSelectedPerms(new Set((data??[]).map((x:any)=>x.permission_id)))}else setSelectedPerms(new Set());setOpen(true)}
 async function save(){if(!activeOrg||!name.trim())return;setError('');try{let roleId=selected?.id;if(selected){const {error}=await supabase.from('roles').update({name:name.trim(),description:description||null,structure_group:group||'Administration',reports_to_role_id:reportsTo||null}).eq('id',selected.id);if(error)throw error;}else{const {data,error}=await supabase.from('roles').insert({organisation_id:activeOrg.id,name:name.trim(),description:description||null,is_system_role:false,sort_order:roles.length+1,structure_group:group||'Administration',reports_to_role_id:reportsTo||null}).select('id').single();if(error)throw error;roleId=data.id;}if(roleId){await supabase.from('role_permissions').delete().eq('role_id',roleId);if(selectedPerms.size){const {error}=await supabase.from('role_permissions').insert([...selectedPerms].map(permission_id=>({role_id:roleId,permission_id})));if(error)throw error;}}setOpen(false);await load()}catch(e:any){setError(e?.message||'Unable to save role')}}
 async function archiveRole(role:Role){if(role.is_system_role){alert('System roles cannot be removed. You can edit their permissions instead.');return}if((counts[role.id]||0)>0){alert('Move users out of this role before deleting it.');return}if(confirm(`Delete role “${role.name}”?`)){const {error}=await supabase.from('roles').delete().eq('id',role.id);if(error)alert(error.message);else load()}}
 async function assign(userId:string,roleId:string){const {error}=await supabase.from('organisation_users').update({role_id:roleId||null}).eq('id',userId);if(error)alert(error.message);else load()}
 const modules=useMemo(()=>[...new Set(perms.map(p=>p.module_key))],[perms]);
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">Organisation Structure & Roles</h1><p className="text-sm text-slate-500">Create roles, define permissions and assign administrators to the organisation structure.</p></div><button onClick={()=>edit()} className="btn-primary"><Plus className="h-4 w-4"/>Create Role</button></div>
 <div className="grid gap-4 lg:grid-cols-2"><section className="card overflow-hidden"><div className="border-b p-4"><h2 className="font-semibold"><Shield className="mr-2 inline h-4 w-4"/>Roles</h2></div><div className="divide-y">{roles.map(r=><div key={r.id} className="flex items-center justify-between gap-3 p-4"><div><div className="flex items-center gap-2"><p className="font-medium">{r.name}</p>{r.is_system_role&&<span className="rounded bg-slate-100 px-2 py-0.5 text-xs">System</span>}</div><p className="text-sm text-slate-500">{r.description||'No description'} · {r.structure_group||'Administration'} · {counts[r.id]||0} user(s)</p><p className="text-xs text-slate-400">Reports to: {roles.find(x=>x.id===r.reports_to_role_id)?.name||'Top level'}</p></div><div className="flex gap-1"><button onClick={()=>edit(r)} className="rounded p-2 hover:bg-slate-100"><Pencil className="h-4 w-4"/></button><button onClick={()=>archiveRole(r)} className="rounded p-2 hover:bg-red-50 hover:text-red-600"><Archive className="h-4 w-4"/></button></div></div>)}</div></section>
 <section className="card overflow-hidden"><div className="border-b p-4"><h2 className="font-semibold"><Users className="mr-2 inline h-4 w-4"/>User assignments</h2><p className="text-xs text-slate-500">This represents who holds each operational role in the club.</p></div><div className="divide-y">{users.map(u=><div key={u.id} className="grid gap-2 p-4 sm:grid-cols-[1fr_220px] sm:items-center"><div><p className="font-medium">{u.profiles?.first_name} {u.profiles?.last_name}</p><p className="text-xs text-slate-500">{u.profiles?.email}</p></div><select className="input" value={u.role_id||''} onChange={e=>assign(u.id,e.target.value)}><option value="">No role</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div>)}</div></section></div>
 <Modal open={open} onClose={()=>setOpen(false)} title={selected?'Edit role':'Create role'} size="xl" footer={<><button className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary" onClick={save}><Save className="h-4 w-4"/>Save role</button></>}><div className="space-y-5">{error&&<div className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="grid gap-4 md:grid-cols-2"><label><span className="label">Role name</span><input className="input" value={name} onChange={e=>setName(e.target.value)}/></label><label><span className="label">Description</span><input className="input" value={description} onChange={e=>setDescription(e.target.value)}/></label><label><span className="label">Structure group</span><input className="input" value={group} onChange={e=>setGroup(e.target.value)} placeholder="Committee, Finance, Operations…"/></label><label><span className="label">Reports to</span><select className="input" value={reportsTo} onChange={e=>setReportsTo(e.target.value)}><option value="">Top level / no parent role</option>{roles.filter(r=>r.id!==selected?.id).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></div><div><h3 className="font-medium">Permissions</h3><p className="text-xs text-slate-500">Select exactly what this role can do. Changes affect users assigned to the role.</p><div className="mt-3 max-h-[430px] space-y-4 overflow-y-auto rounded-lg border p-4">{modules.map(m=><div key={m}><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">{m}</p><div className="grid gap-2 md:grid-cols-2">{perms.filter(p=>p.module_key===m).map(p=><label key={p.id} className="flex gap-2 rounded border border-slate-100 p-2"><input type="checkbox" checked={selectedPerms.has(p.id)} onChange={e=>setSelectedPerms(prev=>{const n=new Set(prev);e.target.checked?n.add(p.id):n.delete(p.id);return n})}/><span><span className="block text-sm font-medium">{p.key}</span><span className="block text-xs text-slate-500">{p.description}</span></span></label>)}</div></div>)}</div></div></div></Modal></div>}
